### ISSUE TITLE
implement CAN mcu_periph for STM32F4 [$5]

### ISSUE THREAD

**Issue by flixr** [paparazzi/paparazzi#1005]
The STM32 implementation for the CAN mcu_periph (HAL) can currently only handle STM32F1.
We need to add support for STM32F4.

This would be used/needed for e.g. ESC32 CAN motor controller support on F4 (see #1004) or intermcu via CAN.

**Comment by OpenUAS** [comment]
* Can ;) do FBW - AP testing over can with two Lisa/Mv2 if useful. 
* Also can perform a can test on other device I'll then buy, no clue what yet

**Comment by OpenUAS** [comment]
It is now set for overnext release :(, Is there anything I can test so it makes it in next release?

**Comment by flixr** [comment]
Closing as we have basic CAN support for F4 now with #1670
