### ISSUE TITLE
cleanup/document altitude definitions: ellipsoid vs. geoid (msl)

### ISSUE THREAD

**Issue by flixr** [paparazzi/paparazzi#1006]
Currently we are mixing up different altitude definitions in some cases/messages which clearly needs to be consolidated, cleaned up and documented.

We usually have global altitude as either
- alt above WGS84 reference ellipsoid
- Height above Mean Sea Level (hmsl), so altitude above geoid)

See also differences explained at https://wiki.paparazziuav.org/wiki/Altitude_definitions

Some things to check/fix/consolidate/document:
- fixedwing waypoint altitude seems to be passed as hmsl
- LLA coordinates usually have alt above ellipsoid (gps datum)
- in UtmCoor_f struct we say that alt is above ellipsoid (and assume that in conversion functions), but seems it is filled with hmsl in some cases
- etc...

[LtpDef] (http://docs.paparazziuav.org/v5.2/structLtpDef__f.html) has alt above ellipsoid in LLA coordinates and an addtional hmsl field

**Comment by flixr** [comment]
Do we need to keep this open? At least the current state is documented...
@dewagter what do you think?

**Comment by dewagter** [comment]
I think ellipsoid / geoid is quite clear.

- relative / absolute is a problem tough
- baro/gps is also not obvious

This issue can be closed, but at some point an update an update in the
altitude would be desirable

class Altitude
{
  enum { ELLIPSOID, MEAN_SEA_LEVEL, LOCAL_AIRFIELD }
  enum { BAROMETRIC, GPS, GROUND_SENSOR }
  get() {

  }
}





-Christophe

**Comment by kirkscheper** [comment]
I am a bit confused with the utm alt... in the definition of the struct it states "in meters above WGS84 reference ellipsoid" but in state.c, the reference frame is set using hmsl (void ins_float_invariant_init(void):216). Shouldn't we just stick to one? The two are quite confusing.

**Comment by flixr** [comment]
@kirkscheper maybe we shouldn't specify the alt reference in the `UtmCoor_f` definition, as it can be use to represent altitude wrt. different references (geoid, ellipsoid, ground, ...)

**Comment by kirkscheper** [comment]
If it isn't consistently used, it may be more clear not to have a height in that structure at all, haha. Users would have to get the altitude from another place (lla for above ellipsoid, ins for ground, gps for geoid). Or alternatively... store the height somewhere readily available in each format (if available) in the state.c using a similar bit set method used for the other formats.

**Comment by flixr** [comment]
There is no simple solution for this... sometimes you simply need ellipsoid alt (e.g. converting to ECEF) and sometimes geoid/msl alt.
Same goes for LLA/LLH actually...

And you don't always have information for both ellipsoid and geoid.
IMHO the best we can do is to document in which cases what is used...

**Comment by kirkscheper** [comment]
:'(
