### ISSUE TITLE
If ARDrone2 does not take off, GCS provides no information on the why

### ISSUE THREAD

**Issue by kevindehecker** [paparazzi/paparazzi#1011]
During my tests it regularly happens that the drone will not start engines. Sometimes the flight plan log will show that it went to mayday - kill, sometimes it just indicates start engine was successful but it wasn't.

In many cases, I actually did something wrong, in other cases I still don't know what the reason may have been (I reboot until it works again). 

In both cases it would be very nice to know why a particular action was not performed by e.g. mentioning it in the flight plan log in GCS. At least in case of a user mistake this should be doable, I reckon that the following causes (that happened to me) can be easily recognized:
-no link 
-gps initialization not ready
-AHRS initialization not ready  
-joystick switch still in ATT instead of NAV mode
-no rc

I suggest the GCS flight plan log, because this would be a central place in which all these problems can be shown. Otherwise, the user has to know where to look, which for novice users is unworkable. (e.g., no link is already shown in GCS by this tiny red bar.... which took me some months to discover)
##

**Comment by OpenUAS** [comment]
Software improvment could help. Also an instructional document and video like "GCS for starters" explaining pitfalls would be welcomed.

Note that in a flightplan block the current line executed is highlighted and shows where it can not continue.

**Comment by gautierhattenberger** [comment]
closing, ardrone2 had motors issue, but this frame is outdated now
