### ISSUE TITLE
Add more selectable modes

### ISSUE THREAD

**Issue by agressiva** [paparazzi/paparazzi#1029]
Add at least two more selectable MODE to rotorcraft and fixedwing
When using AP for pro use its interesting to have at least 4 selectable modes.
For exemple:
Rotorcraft
MANUAL - ATT-DIRECT
MODE1 - ATT-ZHOLD
MODE2 - HOME
MODE3 - NAV

Fixedwing
MANUAL - 
HOME - back to home and MOB
AUTO1 - ATT-DIRECT
AUTO2 - a mode that the roll stick control roll_sp, pitch stick control a climb_rate, throttle control the airspeed setpoint and yaw control course_sp.
This mode is util for FPV or when remote piloting aircraft.
AUTO3 - NAV

I think another good idea is a mode that can select an specific NAV block (mission module)

this way you not need the laptop to do some basic procedures.
##

**Comment by podhrmic** [comment]
Directly related to  #1975
Maybe we can close this then?
