### ISSUE TITLE
GCS Speech spams GPS accuracy

### ISSUE THREAD

**Issue by EwoudSmeur** [paparazzi/paparazzi#1046]
When the GPS accuracy is between ~15 - 25m the GCS speech program will tell everytime the accuracy changes a bit. This results in spamming of the first words of the sentence, not even hearing what the accuracy even is. Requiring a change of more than ~5m could solve this issue.

The underlying issue is that the speech program repeats messages before it has finished speaking (same with low battery, it spams the name of the vehicle without ever reaching the battery voltage statement)

**Comment by flixr** [comment]
Would probably require to save the last announced pacc per aircraft and then check that in `get_svinfo` in live.ml

**Comment by flixr** [comment]
@EwoudSmeur @OpenUAS if you are happy with the solution of #1129 we can backport it to v5.4 and close this issue...

**Comment by flixr** [comment]
backported to v5.4 with 3e4169c
