### ISSUE TITLE
It should be possible to select which of multiple a/c are seen in each GCS window

### ISSUE THREAD

**Issue by alonsoac** [paparazzi/paparazzi#1056]
I would like to be able to monitor 2 or more a/c each one in a separate GCS window. 

One way to do this could be to add a -aircraft_id parameter to gcs so that only messages for that a/c are received.
Another more user friendly way could be in the GCS aircraft menu add a Hide item that would completely hide all information from all sections of the GCS window for that aircraft.

**Comment by OpenUAS** [comment]
There is a GCS parameter -auto_hide_fp  is this of help?

**Comment by alonsoac** [comment]
The problems with having multiple a/c in the window when only one needs to be monitored include:
 - alerts from other aircrafts are mixed in with the monitored a/c
 - wind information is mixed from different sources when only interested in monitored a/c
 - papgets mix data from different a/c
 - it is not possible to hide the strips for other aircrafts or at least have the selected aircraft show on top
- it is possible to click on the wrong a/c and make a flight plan change
- it is not easy to go back to the previous location and zoom after having to change it to see another a/c
There are multiple use cases. Someone might want to auto hide fp and strips but keep seeing alerts for all a/c.
It may be possible to make the GCS more robust so that multiple a/c can be monitored easily from just one window but I figure it would be easier first to select only one and then open more windows to monitor other a/c if needed.

**Comment by OpenUAS** [comment]
Thanks for the good issue description. I also see it as benificial. How to implement best is open for discussion add remarks to this issue plz.
