### ISSUE TITLE
Cannot compile Compass

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#1067]
In the dir ~/paparazzi/sw/ground_segment/cockpit/there is compass.ml. To be able to use it one must compile the source via:

    $  make compass

This gives

    OL compass
    ocamlfind: Package `pprz.xlib' not found
    make: *** [compass] Error 2

**Comment by gautierhattenberger** [comment]
If you set `PAPARAZZI_SRC` and `PAPARAZZI_HOME` correctly, it is compiling (and running)
