### ISSUE TITLE
GCS Window is blank

### ISSUE THREAD

**Issue by shehroze37** [paparazzi/paparazzi#1070]
When I follow the steps to run paparazzi on Ubuntu and GCS window starts, its just blank. I cant do anything with it and there are no home and setting buttons on the screens and no GPS or flight data appears at the bottom. Whats going wrong here ??

**Comment by flixr** [comment]
See https://wiki.paparazziuav.org/wiki/FAQ#Why_do_I_only_get_a_blank_.28black.29_GCS
Also please use the mailing list for questions like this https://wiki.paparazziuav.org/wiki/Contact

**Comment by OpenUAS** [comment]
@shehroze37, flixr answer will surely solve your issue.
