### ISSUE TITLE
ac_id is converted to int in messages_tool.py

### ISSUE THREAD

**Issue by gtoonstra** [paparazzi/paparazzi#1072]
At around line 69, the messages_tool converts the ac_Id to an int in the messagesinterface class. This generates a ValueError exception, which is then passed. the messages tool is a python port of the messages window and usually only displays telemetry info, which is why it's probably the correct behavior.
In a different script in python I wanted to reuse the messagesinterface class (the class connecting python to ivy), but also forward messages of any type (ground, datalink, etc). 
We should probably include an option to the initializer to indicate which type of messages should be passed (a list of the types?), which is then matched against the ac_id to see if it should call the callback, then pass it as a string?

**Comment by flixr** [comment]
How about the solution proposed in #1073 ?
