### ISSUE TITLE
GCS Window is blank sometimes in simulation

### ISSUE THREAD

**Issue by alonsoac** [paparazzi/paparazzi#1078]
I am working with updated master. Sometimes when I do a simulation I can see messages in the Message window but the GCS stays blank. Closing gcs and running it again always solves the problem.

**Comment by gautierhattenberger** [comment]
I suspect that sometimes server and GCS getting out of sync at startup (server miss the AIRCRAFTS request and GCS miss the NEW_AIRCRAFT message). Not really a bug, just a timing issue.

**Comment by flixr** [comment]
How about just re-sending the AIRCRAFTS request from the GCS if it was not answered?

**Comment by OpenUAS** [comment]
Super, a fix will leave a lot of beginning PPRZ users a lot less confused.

**Comment by alonsoac** [comment]
Thanks
