### ISSUE TITLE
ERROR while trying to install on Mac Yosemite

### ISSUE THREAD

**Issue by darryljackman** [paparazzi/paparazzi#1091]
After following the prereq's carefully, I still get the following error when tying to actually install.

Have searched and searched and can't find anything that helps!!

The following is what i ran/results:

Darryls-MacBook-Pro:paparazzi-master darryljackman$ cd ~/paparazzi && make && ./paparazzi

Building Paparazzi version v5.5_devel-135-gc3abe89

/Applications/Xcode.app/Contents/Developer/usr/bin/make -C data/maps

DOWNLOAD: google maps version code
/bin/sh: gsed: command not found
Extracted google maps version was not a valid number: 
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C sw/lib/ocaml
OC cserial.c
clang: error: unknown argument: '-fno-defer-pop'
make[1]: *** [cserial.o] Error 2
make: *** [libpprz] Error 2
Darryls-MacBook-Pro:paparazzi darryljackman$

**Comment by flixr** [comment]
Regarding the `-fno-defer-pop` see https://github.com/paparazzi/paparazzi/issues/835
But please use the mailing list for questions like this.
This issue tracker is meant for bug/feature tracking...
