### ISSUE TITLE
MAVLINK wrapper for IVY

### ISSUE THREAD

**Issue by podhrmic** [paparazzi/paparazzi#1106]
(so Paparazzi can talk to QGroundControl http://qgroundcontrol.org/)
I know the wrapper already exists, but I am unsure about how well it works with current master.
Splitted items from wishlist #620 (as recommended by @OpenUAS)
(For Paparazzi 6.0)

**Comment by flixr** [comment]
Sounds like a duplicate of #13 (and #119), so I think we can close this one...
Or were you thinking of something else?

**Comment by podhrmic** [comment]
True, sorry haven't seen the older issues.
