### ISSUE TITLE
Full support for Parrot Bebop

### ISSUE THREAD

**Issue by flixr** [paparazzi/paparazzi#1149]
This meta issue is to track progress of the Parrot Bebop support for autonomous flight

- [x] motor controllers
- [x] bat voltage
- [x] IMU (MPU6050)
- [x] mag (AKM 8963)
- [x] baro (MS5607)
- [x] GPS (Furuno GN-87F)
- [x] sonar

See also issue #1163 for the camera support tracking

**Comment by gautierhattenberger** [comment]
basic all sensors are now supported
