### ISSUE TITLE
Camera hardware support for Parrot Bebop

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#1163]
This meta issue is to track progress of the Parrot Bebop support for the build in camera hardware
- [x] bottom camera
- [x] front camera
- [x] ISP video processor
- [x] H264 video encoder
- [x] GPU
##

**Comment by OpenUAS** [comment]
Any new insights @fvantienen , if so plz assign it to milestone 5.8 if it is feasable else v6.0, but that would be less fun ;)

**Comment by dewagter** [comment]
- GPU is supported, but what do you want to run on the GPU?
 - ISP and H264 require quite some library files.

**Comment by flixr** [comment]
So ISP is implemented with #1750 thanks to @fvantienen

**Comment by OpenUAS** [comment]
Big fat **THANKS** to @fvantienen for adding all the magic by sleepless nights spells. Superb! The next step, separation and refactoring is already ongoing for an even cleaner solution
