### ISSUE TITLE
Paparazzi center minimum size too restrictive

### ISSUE THREAD

**Issue by flixr** [paparazzi/paparazzi#1167]
On small screens the minimum size (width) of the paparazzi center is way to restrictive (too wide).

It should be possible to resize it to a smaller width, but somehow this limited by the default width of the combo boxes and buttons...
##

**Comment by OpenUAS** [comment]
Lets say 800x600 is our minimum?(or 640x480 then we can go from there to define what "fixed means". Ye in the past I'v tested it on a RPi with touch 320x240 indeed problematic ;)

**Comment by flixr** [comment]
The problem is not choosing a min size... some columns can be made infinitely small. But the right column with target/flashmode/settings drop downs and buttons can't be made small enough.
Not sure how to fix that...

**Comment by hooperfly** [comment]
We could emulate, to some degree, how modern website UI degrades on various device(i.e. a full screen browser on a computer/laptop down to smartphones and all aspect ratios and screen sizes in between.) Usually they degrade into vertically stacked containers. We could also leverage the `layout` technique we use with the GCS to specify a layout model, so to speak for the Paparazzi Center. Currently the Paparazzi Center looks like the following:
![screen shot 2015-11-23 at 8 09 10 pm](https://cloud.githubusercontent.com/assets/10355071/11357686/e67e6eda-921e-11e5-8e35-85cc8df1e1ce.png)

A first order degradation model might be to show the menu bar, followed by the config panel area, followed by the build/execute panel, followed by the status bar.

**Comment by gautierhattenberger** [comment]
the python version can be used and should be smaller
