### ISSUE TITLE
ARdrone2 IMU_Lost often

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#1180]
Using Paparazzi version v5.5_devel-586-g27baff9 ARdrone2 IMU_Lost often. Using ardrone2_raw version v5.2 no the issue. Same hardware, multiple tests.

**Comment by OpenUAS** [comment]
Assigne to self, since issue now under investigation. Will add more sensible info and see I I can pinpoint the cause. It keeps raining Ardrone2's, even when the sun shines ;-)

**Comment by flixr** [comment]
Any updates here?

**Comment by gautierhattenberger** [comment]
It is not clear if we can really do something in about this issue in the end... It looks like a hardware flaw of the ARDrone2. Unless we have more information from Parrot, I would like to close this issue and add a warning about this known issue in the wiki.

**Comment by flixr** [comment]
I'm at least taking it out of the milestone until we have more information to act on....

**Comment by OpenUAS** [comment]
With the new fix of non blocking did not experience it on multiple different AR-Drones 2. The issue with testing was there where multiple other PPRZ issue keeping from having decent test flights. So closed for now, and will reopen if experienced again. @gautierhattenberger , see above Same Hardware, other PPRZ version, so yes we can do something.
