### ISSUE TITLE
MAVlink not integrated yet

### ISSUE THREAD

**Issue by flixr** [paparazzi/paparazzi#119]
Replace the paparazzi messages and transport with [mavlink] (http://qgroundcontrol.org/mavlink/start) or find andonther way to integrate side by side.

also see #13

**Comment by flixr** [comment]
@LodewijkSikkel you worked on improving the current mavlink module, what is the status on that?

**Comment by LodewijkSikkel** [comment]
Almost done, we’ve integrated the bluetooth and UDP stuff in the old module, such that we can write bytes over pprz transport as always. I’ve have to rewrite the messages to be send though, but I expect to be able to do that this week.

On 04 Nov 2015, at 10:03, Felix Ruess <notifications@github.com<mailto:notifications@github.com>> wrote:


@LodewijkSikkel<https://github.com/LodewijkSikkel> you worked on improving the current mavlink module, what is the status on that?

**Comment by flixr** [comment]
Ok, great!
But UDP is working fine in the current version...

**Comment by flixr** [comment]
Closing this as we already have (a basic) mavlink module, which was further improved in #1422.
Of course more functionality can be added...
