### ISSUE TITLE
HOVER and NAV wobble when using stabilization_euler

### ISSUE THREAD

**Issue by agressiva** [paparazzi/paparazzi#1202]
When using stabilization int_euler or float_euler the hover/navigation start wobble 

here the log that show the problem.
https://www.dropbox.com/sh/abo1p42zsfx1k8e/AABjgGWHmkGspIFlX8tJey19a?dl=0
I am using ppz version: v5.5_devel-618-gd9ba218-dirty

Compass calibrated ans tested
H_X, H_Y and H_Z set to mine location.

Here are the steps to reproduce the problem:
Let the rotorcraft in hover and do some disturbance. May be a pitch or roll comand ou push it by hand.

In mine test when the YAW= 0 or 180deg the quad goes back to hover position.
When yaw is around 90 or -90deg the quad start wooble very similar to when  compass is uncalibrated.

**Comment by flixr** [comment]
duplicate of #1201 ?

**Comment by flixr** [comment]
And you only have the problem with euler stabilization?
Why use euler in the first place (instead of the quaternion version)?

Also the log is from Quad680 with float_euler stabilization and float_mlkf ahrs...

**Comment by agressiva** [comment]
Hi Felix, i ever used quaternion  but last week i do some flightplans using YAW command and found a problem with this stabilization.

Every time i use the YAW the quad do some strange and dangerous maneuver so i changed to euler and i get another problems.

**Comment by flixr** [comment]
Did you test #1170 (which should bring some improvements)?

**Comment by flixr** [comment]
From the log it looks like you request a higher yaw rate than the quad can manage...

**Comment by agressiva** [comment]
Felix, i tested using #1170 without any result.

about yaw rate, yes ... quad not support that acceleration.
I do some adjusts in reference to do the tests.

**Comment by OpenUAS** [comment]
The hint by @flixr about to high a to high yaw rate is also in our experience cause for "Wobble". Let us know via this issue it adjusting the thing mentioned fix your issue and add comment to this issue please, that would be great.

**Comment by agressiva** [comment]
I do some more tests with another quadcopter and it worked fine.
The problem is related to mine hardware.

**Comment by agressiva** [comment]
tested with stabilization int and float. 
work perfect.
