### ISSUE TITLE
add copy AC menu item to paparazzi center

### ISSUE THREAD

**Issue by flixr** [paparazzi/paparazzi#1209]
I think it would be nice to add a "A/C->Copy" menu item to the Paparazzi Center menu additionally to "A/C->New".
Often one starts with one of the existing airframes anyway and goes on to adapt it.
So it would be desirable to have a "copy" option that creates a new A/C entry in conf.xml with the same initial xml files as the currently selected one. Preferably there would also be a dialog to ask if the airframe file of the chosen aircraft should be copied and saved under a new name.

**Comment by TobiasMue** [comment]
great idea!

**Comment by agressiva** [comment]
+1

**Comment by OpenUAS** [comment]
Only if copy is copy it will be handy IMHO, if not the Airframe XML is copied it is more like an alias an will give much confusion(based in hands on with +100 different students using Paparazzi)

**Comment by OpenUAS** [comment]
Squeezing it in for the overnext release because of positive response and usefulness
