### ISSUE TITLE
[paparazzi-center] Generic Airframe drop-down dependent sessions

### ISSUE THREAD

**Issue by esden** [paparazzi/paparazzi#1215]
Currently there is now way to create sessions in the paparazzi-center that are aware which airframe is selected in the drop-down menu. The only session that is aware of that is the '''Simulation''' session.

The '''Simulation session''' is hardcoded in ocaml at the moment.

Motivation:
There is no way to have for example settings application run without creating specific sessions for it as the program takes the ```-ac``` parameter.

Proposal:
Create a "magic" variable that will be replaced by the ocaml code with the selected airframe file in the session command line.

Example:
If you have a session that contains a commandline like:
```
sw/ground_segment/tmtc/settings -ac #AIRCRAFT#
```
it and you have selected the A/C called ```MySuperQuad``` the resulting command call will be:
```
sw/ground_segment/tmtc/settings  -ac MySuperQuad
```

**Comment by flixr** [comment]
Solved with merge of #1217
