### ISSUE TITLE
Fuel indicator not working properly

### ISSUE THREAD

**Issue by cogbot1** [paparazzi/paparazzi#1223]
When installing Paparazzi on a Boeing 737 the fuel indicator is not able to handle the amount of fuel left.

![img_20150627_085932](https://cloud.githubusercontent.com/assets/7021603/8518168/da09ba8a-23c7-11e5-9f4c-db8735d56a70.jpg)

**Comment by cogbot1** [comment]
Update: added a better picture. 
![img_20150627_085902](https://cloud.githubusercontent.com/assets/7021603/8518276/cb0ac87a-23c8-11e5-93c7-49e6b2488800.jpg)

**Comment by flixr** [comment]
Lol, did the HOME mode work at least?

**Comment by flixr** [comment]
Closing as "won't fix" as I will never be able to do even simple desk tests with the 737 ;-)
