### ISSUE TITLE
Bootloader on MX working with latest LibopenCM3

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#1254]
AS a user I want a simple way to upload my AP software to the AP board. the newer Lisa v2 MX has an F4. THe working of flasing by USB are not tested and know to be problematic. Will dig up a board and start testing.

Issue move to https://github.com/paparazzi/luftboot/issues/8

**Comment by podhrmic** [comment]
FYI there already exists a bootloader for Lisa MX https://github.com/podhrmic/aggieair-bootloader but it still has to be merged to the main repo, since it is using older version of libopencm3 and needs to be updated. Again, something I will do after the v5.6 release.

**Comment by podhrmic** [comment]
Shall we move it to milestone v5.8?

**Comment by OpenUAS** [comment]
Moved for a 2nd time is not really the best thing IMHO... I've assigned it to myself so we could also fix it in the lab and a "slight" promise of Piotr ;) Note that it is more for his sake than mine, I still have a bunch of Lisa MX.

**Comment by OpenUAS** [comment]
Well should I just put  a bounty on it ;)

**Comment by OpenUAS** [comment]
move to https://github.com/paparazzi/luftboot/issues/8
