### ISSUE TITLE
ARDrone2  and Bebop SONAR_MAX_RANGE not defined with default value

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#1267]
If use sonar is TRUE then this is also needed and should not be:
```
 <define name="SONAR_MAX_RANGE" value="4.2"/>
```

**Comment by flixr** [comment]
So what should be the default values for ARDrone2 and Bebop?

**Comment by fvantienen** [comment]
It should be +/-4m for both

**Comment by OpenUAS** [comment]
Thx, hop -D there goes my "branch fix_issue_1267" :) . 
As fast as issues are fixed I cannot even say, "As a user I would like to.." ;)
