### ISSUE TITLE
video_usb_logger and image path incorrect

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#1289]
To be able to save photoshots, to USB stick while flying ARDRone2 autonomous the image save path must be able to be set and is not working. hint: STRINGYFY adds Double quotes

**Comment by OpenUAS** [comment]
Major since it defeats a little the purpose of the module if not working ;)

**Comment by fvantienen** [comment]
This module is working fine without it, next to that almost nobody uses this module. I think it is a major problem that we have major labels..
But next to that I was going to push this fix so maybe there wasn't even the need to add an issue for this, as I already fixed it..
