### ISSUE TITLE
GPS based heading estimation for ahrs cmpl_quat

### ISSUE THREAD

**Issue by flixr** [paparazzi/paparazzi#130]
To use the ahrs int_cmpl_quat (or float_cmpl) without a magnetometer on fixedwings we need yaw correction based on GPS heading...

**Comment by OpenUAS** [comment]
Tested auto2 in Fixedwing the float_cmpl_quad. Need some TLC. No time to analyse all yet. Heading handling needs some improvement from my first experience.
