### ISSUE TITLE
A.R.Drone 2.0  program.elf.respawner.sh and program.elf process not killed in time

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#1306]
Using PPRZ version: v5.6.0_stable-2-g7ce6e8a after an upload of default ardrone2 example the main ap.elf process starts but before these processes are killed:

* /bin/sh /bin/program.elf.respawner.sh -360p.slices 0 -live.tcp 
* /bin/program.elf -360p.slices 

Manually via telnet killing the processes and restarting the ap.elf all is OK
Using v5.5.2_testing ( 609d3a0) this behaviour was not observed.

NOTE: adding a  linux wait or waitpid could be of help

**Comment by OpenUAS** [comment]
Message to self: in mcu_arch_init() the board_init() is after threaded inits and for ARDRone2, default Processes must be killed first(bettereven gracefully)

**Comment by flixr** [comment]
thx, fixed with #1307
