### ISSUE TITLE
viewvideo: netcat option is broken

### ISSUE THREAD

**Issue by flixr** [paparazzi/paparazzi#1312]
The `VIEWVIDEO_USE_NETCAT` option of the `viewvideo_rtp_stream` module is broken, it doesn't even compile...

Plz either fix it or we remove it completely...

See also #1293

**Comment by gautierhattenberger** [comment]
This was actually my doing for last imav. I'll have a look.

**Comment by OpenUAS** [comment]
It's was used and to be honest quite useful...

**Comment by flixr** [comment]
@gautierhattenberger would be nice if you could fix this for the v5.8 release.

**Comment by flixr** [comment]
Should be fixed with #1426
