### ISSUE TITLE
natnet2ivy integer truncated

### ISSUE THREAD

**Issue by dewagter** [paparazzi/paparazzi#1335]
@fvantienen 

natnet2ivy.c: In function ‘sample_data’:
natnet2ivy.c:575:3: warning: large integer implicitly truncated to unsigned type [-Woverflow]
   bytes_data += udp_socket_recv(&natnet_data, buffer_data, MAX_PACKETSIZE);
   ^

**Comment by flixr** [comment]
@fvantienen would be great if you could fix this before the v5.8 release...

**Comment by gautierhattenberger** [comment]
this was actually fixed with e9179964a4215a6655fe248a843627ba8eb87d6f
