### ISSUE TITLE
server: doesn't send DL_VALUES if there are a lot of settings

### ISSUE THREAD

**Issue by flixr** [paparazzi/paparazzi#1344]
When you add more settings, at some point server doesn't send DL_VALUES anymore with
`Discarding long ivy message DL_VALUES (1240 bytes)`

What is this Ivy bug the limit of 1000 chars in `message_send` in pprz.ml is supposed to prevent?

**Comment by flixr** [comment]
@gautierhattenberger @alex31 any idea why there is this limitation?

**Comment by gautierhattenberger** [comment]
Actually, Ivy should support long messages since 2008, but Pascal added this check in 2009. We should try to remove it and see because their is no reasons to keep it from what I can see.

**Comment by flixr** [comment]
So what is the maximum length now?
I guess it would still make sense to prevent endlessly long messages?

**Comment by gautierhattenberger** [comment]
there is an initial malloc and a realloc if needed, so I guess the limit is the available memory... but yes, limiting stupidly long message is probably wise
the initial alloc is around 4000 bytes I think.

**Comment by flixr** [comment]
So we limit it to 4000 or 10000 or so?

**Comment by gautierhattenberger** [comment]
tested and working
