### ISSUE TITLE
pprzcenter autoload issue

### ISSUE THREAD

**Issue by gautierhattenberger** [paparazzi/paparazzi#1381]
The automatic re-loading of conf seems to have some side effects:
- the flash mode is reset to default each time the upload button is pressed, so you can't really use it anymore
- if an airframe file is missing or corrupted, the flight plan file is not displayed either (it was the case before) but when changing back to another valid aircraft, it keeps failing for these two files

**Comment by flixr** [comment]
The flash mode should be fixed, @gautierhattenberger could you plz take a look at the second problem?
