### ISSUE TITLE
GCS - Papgets not visible on GCS screen : Mac OS X El Capitan

### ISSUE THREAD

**Issue by hooperfly** [paparazzi/paparazzi#1395]
It seems that the homebrew gtk library now runs natively on Mac OS X as of El Capitan. As a result, `papgets` are not visible on the GCS but they are active. The place/location where a given papget is placed will activate the appropriate action when pressed but the `papaget` icon is not visible.

Screen capture of GCS using GTK+ Quartz library under El Capitan( papgets not showing )

<img width="1340" alt="screen shot 2015-10-28 at 5 08 19 pm" src="https://cloud.githubusercontent.com/assets/10355071/10806876/e054e56c-7d96-11e5-93c7-a66a50721aed.png">

Screen capture of GCS using GTK+ X11 library under Yosimite( papgets visible )

![screen shot 2015-05-18 at 10 47 02 pm](https://cloud.githubusercontent.com/assets/10355071/10806883/ef384088-7d96-11e5-9f88-2f1567996a8f.png)
##

**Comment by hooperfly** [comment]
It looks like there were quite a few changes to papgets related code on Sept. 27th. This could be related to those changes as well.

https://github.com/paparazzi/paparazzi/search?utf8=%E2%9C%93&q=papget

**Comment by gautierhattenberger** [comment]
closing as won't be fixed in current GCS
see https://github.com/paparazzi/paparazzi/projects/2
