### ISSUE TITLE
GCS - Widge "altigraph" not displayed - Mac OS X El Capitan

### ISSUE THREAD

**Issue by hooperfly** [paparazzi/paparazzi#1397]
The `altigraph` widget is not visible/being displayed using the GTK+ Quartz library under Mac OS X El Capitan. The panel/view is effectively blank with no indication that the widget is working. This issues is probably related to the `papgets` display issues also encounterd in this GTK/Mac OS X configuration.
##

**Comment by OpenUAS** [comment]
Likely depends on a fix in GTK lib icw Ocaml, therfore fix not to be expected befor a 5.8 release, sorry

**Comment by gautierhattenberger** [comment]
closing as won't be fixed in current GCS
see https://github.com/paparazzi/paparazzi/projects/2
