### ISSUE TITLE
GCS - Screen refresh flashing during resizing of windows - Mac OS X El Capitan

### ISSUE THREAD

**Issue by hooperfly** [paparazzi/paparazzi#1398]
When resizing the GCS windows/panels or zooming in and out, the window backgrounds flash as well and display artifacts related to movement. Interacting with the window frame is sluggish.

Screen capture of background flashing:
<img width="643" alt="screen shot 2015-10-28 at 6 00 06 pm" src="https://cloud.githubusercontent.com/assets/10355071/10807519/dbcb2bb2-7d9d-11e5-8154-2342e602667a.png">

Screen capture of resizing artifacts:
<img width="737" alt="screen shot 2015-10-28 at 6 00 35 pm" src="https://cloud.githubusercontent.com/assets/10355071/10807522/df6cd450-7d9d-11e5-9d67-aa83d648fd13.png">
##

**Comment by gautierhattenberger** [comment]
closing as won't be fixed in current GCS
see https://github.com/paparazzi/paparazzi/projects/2
