### ISSUE TITLE
Semaphore error listing should show the conf/airframe/target failing

### ISSUE THREAD

**Issue by dewagter** [paparazzi/paparazzi#1402]
##

**Comment by flixr** [comment]
I assume you mean when the scheduler built all confs?
It shows the confs which failed at the end, but there is no immediately easy way to show a summary of which aircrafts failed.

If you want to have a go at this, look at the `test_all_confs` target in the main Makefile.

**Comment by gautierhattenberger** [comment]
it already shows failing conf
