### ISSUE TITLE
Compilation problem ms5611 baro spi

### ISSUE THREAD

**Issue by fr4ngus** [paparazzi/paparazzi#1408]
I try to use the ms5611 baro but when I try to compile I have the following errors:

modules/sensors/baro_ms5611_spi.c:40:24: error: 'spi1' undeclared (first use in this function)
 #define MS5611_SPI_DEV spi1
                        ^
modules/sensors/baro_ms5611_spi.c:61:34: note: in expansion of macro 'MS5611_SPI_DEV'
   ms5611_spi_init(&baro_ms5611, &MS5611_SPI_DEV, MS5611_SLAVE_IDX, FALSE);
                                  ^
modules/sensors/baro_ms5611_spi.c:40:24: note: each undeclared identifier is reported only once for each function it appears in
 #define MS5611_SPI_DEV spi1
                        ^
modules/sensors/baro_ms5611_spi.c:61:34: note: in expansion of macro 'MS5611_SPI_DEV'
   ms5611_spi_init(&baro_ms5611, &MS5611_SPI_DEV, MS5611_SLAVE_IDX, FALSE);
                                  ^
modules/sensors/baro_ms5611_spi.c:44:26: error: 'SPI_SLAVE0' undeclared (first use in this function)

For information my version of GCC is 4.8.4

**Comment by flixr** [comment]
`USE_SPI1` and `USE_SPI_SLAVE0` need to be defined...

This is mainly a documentation issue, but it would probably be a good idea to use the configure options to set these defines automatically like in most other modules/subsystems...
