### ISSUE TITLE
Let's use Voting for complex choices

### ISSUE THREAD

**Issue by dewagter** [paparazzi/paparazzi#1413]
Test vote

**Comment by dewagter** [comment]
+1

**Comment by flixr** [comment]
+1

**Comment by flixr** [comment]
test  this as well :+1:

**Comment by rmeertens** [comment]
Did you consider the fact that when having more than two options there is no good voting system? Please consider Arrow's impossibility theorem:  https://en.wikipedia.org/wiki/Arrow's_impossibility_theorem

**Comment by flixr** [comment]
We don't have to use it if there are more than two options....

**Comment by rmeertens** [comment]
So in this issue we can choose for:
- voting for everything
- never voting
- only voting if there are only two options. 

mmm,

**Comment by dewagter** [comment]
If you know a system to vote for 3 or more would be nice:

a) absolutely a good idea (changing signs on spektrum transmitters)
b) no strong opinion (if it makes some people happy to have the correct sign on their transmitter display I'm ok to reverse 3 channels)
c) terribly against (I just sold hundreds of ladybirds and do not want my customers to need to change transmitter signs even if a single define USE_OLD_SPEKTRUM_REVERSED_SIGNS in the airframe can solve the problem)
