### ISSUE TITLE
Pix4Flow not working anymore with new velocity estimation abi messages

### ISSUE THREAD

**Issue by rmeertens** [paparazzi/paparazzi#1415]
Easy to fix: find a way to define the noise. Assign me if you want, but know that the pix4flow module currently does not work.  Assign me if you want, but know that the pix4flow module currently does not work.

**Comment by rmeertens** [comment]
Good enough :+1:

**Comment by flixr** [comment]
For now, yes... still desirable to calculate variance based on current measurement somehow...
