### ISSUE TITLE
Fresh Install compile error

### ISSUE THREAD

**Issue by coppolam** [paparazzi/paparazzi#1428]
Command line output when using "make" after "make clean".

------------------------------------------------------------
Building Paparazzi version v5.7_devel-597-g2258100
------------------------------------------------------------
make -C data/maps
mkdir /home/mario/paparazzi/nexport/conf/maps_data
mkdir: cannot create directory ‘/home/mario/paparazzi/nexport/conf/maps_data’: No such file or directory
make[1]: *** [/home/mario/paparazzi/nexport/conf/maps_data] Error 1
make: [update_google_version] Error 2 (ignored)
[ -L conf/conf.xml ] || [ -f conf/conf.xml ] || cp conf/conf_example.xml conf/conf.xml
[ -L conf/control_panel.xml ] || [ -f conf/control_panel.xml ] || cp conf/control_panel_example.xml conf/control_panel.xml
make -C sw/lib/ocaml
OCY expr_parser.mly
OCL expr_lexer.mll
40 states, 423 transitions, table size 1932 bytes
DEPEND .depend
OC fig.mli
OC fig.ml
OC debug.mli
OC debug.ml
OC base64.mli
OC base64.ml
OC serial.mli
OC serial.ml
OC ocaml_tools.mli
OC ocaml_tools.ml
OC expr_syntax.mli
OC expr_syntax.ml
OC expr_parser.mli
OC expr_parser.ml
OC expr_lexer.ml
OC extXml.mli
OC extXml.ml
OC env.mli
OC env.ml
OC xml2h.mli
OC xml2h.ml
OC latlong.mli
OC latlong.ml
OC egm96.mli
OC egm96.ml
OC srtm.mli
OC srtm.ml
OC http.mli
OC http.ml
OC maps_support.mli
OC maps_support.ml
OC gm.mli
OC gm.ml
OC iGN.mli
OC iGN.ml
OC geometry_2d.mli
OC geometry_2d.ml
OC cserial.c
OC convert.c
OC ubx.mli
OC ubx.ml
OC pprz.mli
OC pprz.ml
OC xbee.mli
OC xbee.ml
OC logpprz.mli
OC logpprz.ml
OC xmlCom.mli
OC xmlCom.ml
OC os_calls.mli
OC os_calls.ml
OC editAirframe.mli
OC editAirframe.ml
OC defivybus.mli
OC defivybus.ml
OC fp_proc.mli
OC fp_proc.ml
OC gen_common.mli
OC gen_common.ml
OL lib-pprz.cma
OC gtk_tools.mli
OC gtk_tools.ml
OC platform.mli
OC platform.ml
OC contrastLabel.mli
OC contrastLabel.ml
OC acIcon.mli
OC acIcon.ml
OC wind_sock.mli
OC wind_sock.ml
GLADE gtk_papget_editor.ml
OC gtk_papget_editor.ml
GLADE gtk_papget_text_editor.ml
OC gtk_papget_text_editor.ml
GLADE gtk_papget_gauge_editor.ml
OC gtk_papget_gauge_editor.ml
GLADE gtk_papget_led_editor.ml
OC gtk_papget_led_editor.ml
OC papget_common.mli
OC papget_common.ml
OC papget_renderer.mli
OC papget_renderer.ml
OC papget.mli
OC papget.ml
OC mapCanvas.mli
OC mapCanvas.ml
OC mapWaypoints.mli
OC mapWaypoints.ml
OC mapTrack.mli
OC mapTrack.ml
OC mapGoogle.mli
OC mapGoogle.ml
OC mapIGN.mli
OC mapIGN.ml
OC ml_gtk_drag.c
OC xmlEdit.mli
OC xmlEdit.ml
OC mapFP.mli
OC mapFP.ml
OL xlib-pprz.cma
OC xml_get.ml
OL xml_get.out
COPY META.pprz.template
OOC fig.ml
OOC debug.ml
OOC base64.ml
OOC serial.ml
OOC ocaml_tools.ml
OOC expr_syntax.ml
OOC expr_parser.ml
OOC expr_lexer.ml
OOC extXml.ml
OOC env.ml
OOC xml2h.ml
OOC latlong.ml
OOC egm96.ml
OOC srtm.ml
OOC http.ml
OOC maps_support.ml
OOC gm.ml
OOC iGN.ml
OOC geometry_2d.ml
OOC ubx.ml
OOC pprz.ml
OOC xbee.ml
OOC logpprz.ml
OOC xmlCom.ml
OOC os_calls.ml
OOC editAirframe.ml
OOC defivybus.ml
OOC fp_proc.ml
OOC gen_common.ml
OOL dlllib-pprz.so
OOL lib-pprz.cmxa
OOC gtk_tools.ml
OOC platform.ml
OOC contrastLabel.ml
OOC acIcon.ml
OOC wind_sock.ml
OOC gtk_papget_editor.ml
OOC gtk_papget_text_editor.ml
OOC gtk_papget_gauge_editor.ml
OOC gtk_papget_led_editor.ml
OOC papget_common.ml
OOC papget_renderer.ml
OOC papget.ml
OOC mapCanvas.ml
OOC mapWaypoints.ml
OOC mapTrack.ml
OOC mapGoogle.ml
OOC mapIGN.ml
OOC xmlEdit.ml
OOC mapFP.ml
OOL dllxlib-pprz.so
OOL xlib-pprz.cmxa
make -C sw/supervision
DEPEND .depend
GLADE gtk_pc.ml
OC gtk_pc.ml
GLADE gtk_process.ml
OC gtk_process.ml
OC pc_common.ml
OC pc_control_panel.ml
OC pc_aircraft.ml
OC paparazzicenter.ml
OL paparazzicenter
make -C sw/ext
  GENHDR  include/libopencm3/efm32/efm32g/irq.json
  GENHDR  include/libopencm3/efm32/efm32gg/irq.json
  GENHDR  include/libopencm3/efm32/efm32tg/irq.json
  GENHDR  include/libopencm3/efm32/efm32lg/irq.json
  GENHDR  include/libopencm3/sam/3u/irq.json
  GENHDR  include/libopencm3/sam/3x/irq.json
  GENHDR  include/libopencm3/sam/3s/irq.json
  GENHDR  include/libopencm3/sam/3n/irq.json
  GENHDR  include/libopencm3/sam/3a/irq.json
  GENHDR  include/libopencm3/lpc13xx/irq.json
  GENHDR  include/libopencm3/lpc43xx/m0/irq.json
  GENHDR  include/libopencm3/lpc43xx/m4/irq.json
  GENHDR  include/libopencm3/lm3s/irq.json
  GENHDR  include/libopencm3/vf6xx/irq.json
  GENHDR  include/libopencm3/stm32/f2/irq.json
  GENHDR  include/libopencm3/stm32/f1/irq.json
  GENHDR  include/libopencm3/stm32/l0/irq.json
  GENHDR  include/libopencm3/stm32/f0/irq.json
  GENHDR  include/libopencm3/stm32/l1/irq.json
  GENHDR  include/libopencm3/stm32/f4/irq.json
  GENHDR  include/libopencm3/stm32/f3/irq.json
  GENHDR  include/libopencm3/lpc17xx/irq.json
  BUILD   lib/stm32/f1
  CP      libopencm3_stm32f1.ld
  CC      adc.c
  CC      adc_common_v1.c
  CC      can.c
  CC      desig.c
  CC      ethernet.c
  CC      flash.c
  CC      gpio.c
  CC      rcc.c
  CC      rtc.c
  CC      timer.c
  CC      mac.c
  CC      mac_stm32fxx7.c
  CC      phy.c
  CC      phy_ksz8051mll.c
  CC      crc_common_all.c
  CC      dac_common_all.c
  CC      dma_common_l1f013.c
  CC      gpio_common_all.c
  CC      i2c_common_all.c
  CC      iwdg_common_all.c
  CC      pwr_common_all.c
  CC      spi_common_all.c
  CC      spi_common_l1f124.c
  CC      timer_common_all.c
  CC      usart_common_all.c
  CC      usart_common_f124.c
  CC      rcc_common_all.c
  CC      exti_common_all.c
  CC      flash_common_f01.c
  CC      usb.c
  CC      usb_control.c
  CC      usb_standard.c
  CC      usb_f103.c
  CC      usb_f107.c
  CC      usb_fx07_common.c
  CC      usb_msc.c
  CC      vector.c
  CC      systick.c
  CC      scb.c
  CC      nvic.c
  CC      assert.c
  CC      sync.c
  CC      dwt.c
  AR      libopencm3_stm32f1.a
  GENHDR  include/libopencm3/efm32/efm32g/irq.json
  GENHDR  include/libopencm3/efm32/efm32gg/irq.json
  GENHDR  include/libopencm3/efm32/efm32tg/irq.json
  GENHDR  include/libopencm3/efm32/efm32lg/irq.json
  GENHDR  include/libopencm3/sam/3u/irq.json
  GENHDR  include/libopencm3/sam/3x/irq.json
  GENHDR  include/libopencm3/sam/3s/irq.json
  GENHDR  include/libopencm3/sam/3n/irq.json
  GENHDR  include/libopencm3/sam/3a/irq.json
  GENHDR  include/libopencm3/lpc13xx/irq.json
  GENHDR  include/libopencm3/lpc43xx/m0/irq.json
  GENHDR  include/libopencm3/lpc43xx/m4/irq.json
  GENHDR  include/libopencm3/lm3s/irq.json
  GENHDR  include/libopencm3/vf6xx/irq.json
  GENHDR  include/libopencm3/stm32/f2/irq.json
  GENHDR  include/libopencm3/stm32/f1/irq.json
  GENHDR  include/libopencm3/stm32/l0/irq.json
  GENHDR  include/libopencm3/stm32/f0/irq.json
  GENHDR  include/libopencm3/stm32/l1/irq.json
  GENHDR  include/libopencm3/stm32/f4/irq.json
  GENHDR  include/libopencm3/stm32/f3/irq.json
  GENHDR  include/libopencm3/lpc17xx/irq.json
  BUILD   lib/stm32/f4
  CP      libopencm3_stm32f4.ld
  CC      adc.c
  CC      adc_common_v1.c
  CC      can.c
  CC      desig.c
  CC      gpio.c
  CC      pwr.c
  CC      rcc.c
  CC      rtc.c
  CC      crypto.c
  CC      crc_common_all.c
  CC      dac_common_all.c
  CC      dma_common_f24.c
  CC      gpio_common_all.c
  CC      gpio_common_f0234.c
  CC      i2c_common_all.c
  CC      iwdg_common_all.c
  CC      pwr_common_all.c
  CC      rtc_common_l1f024.c
  CC      spi_common_all.c
  CC      spi_common_l1f124.c
  CC      timer_common_all.c
  CC      timer_common_f234.c
  CC      timer_common_f24.c
  CC      usart_common_all.c
  CC      usart_common_f124.c
  CC      flash_common_f234.c
  CC      flash_common_f24.c
  CC      hash_common_f24.c
  CC      crypto_common_f24.c
  CC      exti_common_all.c
  CC      rcc_common_all.c
  CC      usb.c
  CC      usb_standard.c
  CC      usb_control.c
  CC      usb_fx07_common.c
  CC      usb_f107.c
  CC      usb_f207.c
  CC      usb_msc.c
  CC      mac.c
  CC      phy.c
  CC      mac_stm32fxx7.c
  CC      phy_ksz8051mll.c
  CC      fmc.c
  CC      ltdc.c
  CC      vector.c
  CC      systick.c
  CC      scb.c
  CC      nvic.c
  CC      assert.c
  CC      sync.c
  CC      dwt.c
  AR      libopencm3_stm32f4.a
  CC      luftboot.c
luftboot.c: In function 'main':
luftboot.c:481:9: note: #pragma message: Luftboot using 12MHz external clock to PLL it to 72MHz.
 #pragma message "Luftboot using 12MHz external clock to PLL it to 72MHz."
         ^
  CC      luftboot.elf
  create  luftboot.bin
  create  luftboot.hex
make -C sw/tools/bluegiga_usb_dongle
Building target: bluegiga_usb_driver
Finished building target: bluegiga_usb_driver
make -C sw/ground_segment/misc
CC davis2ivy
CC kestrel2ivy
CC natnet2ivy
CC sbp2ivy
CC video_synchronizer
CC sbs2ivy
make -C sw/logalizer
DEPEND .depend
OC log_file.ml
OC play_core.ml
OC play.ml
OL play
OC plotter.ml
OL plotter
GLADE gtk_export.ml
OC gtk_export.ml
OCI export.mli
OC export.ml
OC logplotter.ml
OL logplotter
OC sd2log.ml
OL sd2log
CC plotprofile
CC openlog2tlm
cat src/paparazzi | sed s#OCAMLRUN#/usr/bin/ocamlrun# | sed s#OCAML#/usr/bin/ocaml# > paparazzi
chmod a+x paparazzi
make -C sw/ground_segment/cockpit
DEPEND .depend
GLADE gtk_setting_time.ml
OC gtk_setting_time.ml
GLADE gtk_strip.ml
OC gtk_strip.ml
OCI horizon.mli
OC horizon.ml
OCI strip.mli
OC strip.ml
GLADE gtk_save_settings.ml
OC gtk_save_settings.ml
OCI saveSettings.mli
OC saveSettings.ml
OCI page_settings.mli
OC page_settings.ml
OCI pages.mli
OC pages.ml
OCI speech.mli
OC speech.ml
OCI plugin.mli
OC plugin.ml
OCI sectors.mli
OC sectors.ml
OCI map2d.mli
OC map2d.ml
OCI editFP.mli
OC editFP.ml
OC intruders.ml
OCI live.mli
OC live.ml
OC particules.ml
OCI papgets.mli
OC papgets.ml
OC gcs.ml
OL gcs
make -C sw/ground_segment/multimon
CC hdlc.c
CC pprz.c
CC demod_afsk48p.c
CC demod_display.c
CC unixinput.c
CC xdisplay.c
LD multimon
CC pprzlib.c
CC demod_afsk12.c
CC demodml.c
CC mkcostab.c
LD mkcostab
EXEC mkcostab
CC costabi.c
CC gen_hdlc.c
CC ml_hdlc.c
OC demod.ml
OC hdlc.mli
OC hdlc.ml
OLD multimon.cma
make -C sw/ground_segment/tmtc
DEPEND .depend
OC link.ml
OL link
OC server_globals.ml
OC aircraft.mli
OC aircraft.ml
OC wind.mli
OC wind.ml
OC airprox.mli
OC airprox.ml
OC kml.mli
OC kml.ml
OC intruder.mli
OC intruder.ml
OC rotorcraft_server.mli
OC fw_server.mli
OC server.ml
OL server
OC messages.ml
OL messages
OC settings.ml
OL settings
OC dia.ml
OL dia
OC diadec.ml
OL diadec
OC ivy_tcp_aircraft.ml
OL ivy_tcp_aircraft
OC ivy_tcp_controller.ml
OL ivy_tcp_controller
OC broadcaster.ml
OL broadcaster
OC ivy2udp.ml
OL ivy2udp
OL ivy_serial_bridge
OL app_server
OL ivy2nmea
make -C /home/mario/paparazzi/sw/tools/generators
DEPEND .depend
OL gen_aircraft.ml
OL gen_airframe.ml
OL gen_messages.ml
OL gen_ubx.ml
OL gen_mtk.ml
OC gen_flight_plan.ml
OL gen_flight_plan.out
OL gen_radio.ml
OL gen_periodic.ml
OL gen_settings.ml
OL gen_xsens.ml
OL gen_modules.ml
OL gen_autopilot.ml
OL gen_abi.ml
OL gen_srtm.out
make -C sw/simulator
DEPEND .depend
OC gaia.ml
OL gaia
CC fg.c
OC stdlib.mli
OC stdlib.ml
OC data.mli
OC data.ml
OC flightModel.mli
OC flightModel.ml
OC gps.mli
OC gps.ml
OC sim.mli
OC sitl.mli
OC sitl.ml
OC sim.ml
OL sitl.cma
make -C sw/ground_segment/joystick
DEPEND .depend
CC test_sdl_stick.o
BUILD test_stick
CC sdl_stick.o
CC ml_sdl_stick.o
BUILD sdl_stick.so
OC input2ivy.ml
OL input2ivy
GENERATE /home/mario/paparazzi/nexport/var/include/messages.h
GENERATE /home/mario/paparazzi/nexport/var/include/ubx_protocol.h
GENERATE /home/mario/paparazzi/nexport/var/include/mtk_protocol.h
GENERATE /home/mario/paparazzi/nexport/var/include/xsens_protocol.h
GENERATE /home/mario/paparazzi/nexport/var/include/dl_protocol.h
GENERATE /home/mario/paparazzi/nexport/var/include/abi_messages.h
GENERATE /home/mario/paparazzi/nexport/var/include/mavlink/
make: *** /home/mario/paparazzi/nexport/sw/ext: No such file or directory.  Stop.
make: *** [/home/mario/paparazzi/nexport/var/include/mavlink/protocol.h] Error 2

**Comment by flixr** [comment]
Seems like you have exported `PAPARAZZI_SRC` and/or `PAPARAZZI_HOME` incorrectly.
Either remove these env variables or set them correctly.

**Comment by OpenUAS** [comment]
May bad, open a terminal window then

$ nano ~/.bashrc

Look for PAPARAZZI_SRC and PAPARAZZI_HOME and correct the directories found there.

When correct will look like 

 export PAPARAZZI_HOME=~/paparazzi
 export PAPARAZZI_SRC=~/paparazz
