### ISSUE TITLE
support SPI slave mode on STM32F4

### ISSUE THREAD

**Issue by flixr** [paparazzi/paparazzi#1436]
Only implemented for F1 at the moment....
See also #326

**Comment by kirkscheper** [comment]
Have code for this at https://github.com/kirkscheper/paparazzi/tree/spi_slave.

Waiting for some hardware to come in to test this before pushing.

**Comment by OpenUAS** [comment]
Hardware supplied :)

**Comment by flixr** [comment]
Should be closed with #1456
