### ISSUE TITLE
Support Spektrum serial on LPC21xx arch

### ISSUE THREAD

**Issue by scdwyer** [paparazzi/paparazzi#145]
This would be a useful feature for many I think. While it would use up one of the UARTs, the GPS could perhaps be used on an i2c bus (probably not with an IMU on it). One thing to consider is that the uBlox receivers can only handle a max clock speed of 100kHz on the i2c bus (at least uBlox 5 series). However, there may be other reasons for a free UART, like using serial over usb, or some sort of SPI radio.

This means gps_i2c would need to be revived. (Also see Issue #146).

Another option would be some translation between a UART and PPM, like a PPM Encoder for Spektrum satellites, but this adds more hardware and failure points. On the other hand, if the intermediate hardware handles more than one serial port, you could have multiple satellites for R/C redundancy.

Thoughts? @lamestllama I believe there was some discussion about this, as you did the spektrum code?

**Comment by OpenUAS** [comment]
Needs testing See also #884

**Comment by gautierhattenberger** [comment]
Would it possible to close this as a 'won't fix' since lpc is not a major concern anymore and I personally won't spend time on this ?

**Comment by flixr** [comment]
Agreed. If someone wants to implement this, we are of course still accepting pull requests ;-)
