### ISSUE TITLE
gpsd not in make by default

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#1460]
As I user choosing gpsd from Paparazzi center the GPSD tool expect it to run and does not.
 $ make gpsd2ivy
fixes that but IMHO it should be compiled by default with pprz make.

**Comment by flixr** [comment]
It is deliberately not compiled with make, since you might not have the gpsd dependency installed...
See also #615

**Comment by OpenUAS** [comment]
Ah thank.. now I recall what it was.. :+1:

**Comment by flixr** [comment]
So we can close this again?
Or do you want to add something that will auto-detect whether it could be compiled?
