### ISSUE TITLE
In the flight plan, specify relative waypoints in ENU

### ISSUE THREAD

**Issue by EwoudSmeur** [paparazzi/paparazzi#1526]
Currently, relative waypoints are handled as UTM coordinates. These coordinates do not translate one to one to ENU coordinates. In some cases, it can be very useful to be able to specify that waypoints should be interpreted as ENU, instead of UTM. 
##

**Comment by Fabien-B** [comment]
Done in #2676.
to use it, add the attribute `wp_frame="LTP"` to the flight_plan node (next to `lat0` and `lon0`).
