### ISSUE TITLE
AP_MODE_HOVER_DIRECT mode (actually all hover modes) doesn't set velocity from rc

### ISSUE THREAD

**Issue by kirkscheper** [paparazzi/paparazzi#1549]
The wiki says this about hover mode:

AP_MODE_HOVER_DIRECT (HOVER) 

The rotorcraft hovers at the horizontal position you were at when entering this mode (position control). You still set the throttle directly with your RC. Yaw command on the RC allows for heading change. If USE_SPEED_REF=1 then pitch and roll commands in the RC control speed according to max speed set with REF_MAX_SPEED in the GUIDANCE_H section of airframe file. 

However pprz doesn't do that. guidance_h.sp.mask 4 and 5 are not set to speed is not controlled by rc. I guess someone forgot to add SetBit(guidance_h.sp.mask, 4); SetBit(guidance_h.sp.mask, 5); somewhere...

**Comment by flixr** [comment]
Thanks for finding and reporting this Kirk!
I'm afraid that was my bad...
