### ISSUE TITLE
support multiple IMUs running simultaneously

### ISSUE THREAD

**Issue by flixr** [paparazzi/paparazzi#1585]
Currently there is no proper way to support multiple IMU drivers running simultaneously.
This would be useful for cases where you e.g. want to compare the data from different IMUs, maybe switch to one with less vibrations, switch between external and internal mag, etc...

The IMU drivers already publish the sensor data via ABI using their own ID and the subscribers (e.g. AHRS) can select which one to use.

The main remaining problems are the single global `imu` struct and single IMU calibration.
- [ ] get rid of global `imu` struct
  - each driver keeps it's own copy of the scaled measurements and publishes those via ABI
- [ ] each driver uses their own scale functions or at least their own IMU_x_SENS/NEUTRAL defines
- [ ] send telemetry IMU messages without using the global `imu` struct
  - means adding an IMU/component id to the messages to distinguish?
  - means a lot of duplicated send message code?
  - or subscribe to one specific (e.g. primary or currently active) IMU in `imu.c` and publish those?
- [ ] `BODY_TO_IMU` for each IMU, just like the sensitivity/neutrals
  - howto use `imu_SetBodyToImuCurrent` for each IMU separately?
- [ ] run ahrs_aligner for multiple IMUs separately?
##

**Comment by gautierhattenberger** [comment]
done with #2890
