### ISSUE TITLE
AR Drone 2 ftplib.error_perm

### ISSUE THREAD

**Issue by justing88** [paparazzi/paparazzi#1596]
Hello,

I am receiving the following error when trying to upload the rotorcraft_basic flight plan to the AR Drone 2. I have done this many times before and this error popped up out of the blue.

FTP UPLOAD ERROR: Maybe your ARDrone memory is full? <class 'ftplib.error_perm'>

I tried looking into what is causing it. It says AR Drone memory might be full, but when I telnet to the drone there is available disk space. I am unsure about where this memory is that the message is referring to. Is there a particular directory I should clean out perhaps? The drone reset button did nothing.

Then we tried running uploading to the drone through multiple machines with Paparazzi, and received the same error message.

Here is where it is coming from in parrot_utils.py

```
> #Upload ftp and catch memory-full error
> def uploadfile(ftp, filename, content):
>     try:
>         ftp.storbinary("STOR " + filename, content)
>     except ftplib.error_temp:
>         print("FTP UPLOAD ERROR: Uploading FAILED: Probably your ARDrone memory is full.")
>         sys.exit()
>     except:
>         print("FTP UPLOAD ERROR: Maybe your ARDrone memory is full?", sys.exc_info()[0])
>         sys.exit()
```

I looked up the storbinary() in ftplib.py and got lost.

Here is what the error looks like in Paparazzi

make[1]: Leaving directory `/home/justin/paparazzi/sw/airborne'
cd sw/airborne; make TARGET=ap upload
make[1]: Entering directory`/home/justin/paparazzi/sw/airborne'
Kill running ap.elf and make folder paparazzi
Uploading 'ap.elf' from /home/justin/paparazzi/var/aircrafts/ardrone2/ap to paparazzi
# pragma message: Please wait, uploading can take some time...

**FTP UPLOAD ERROR: Maybe your ARDrone memory is full? <class 'ftplib.error_perm'>**
======================== ARDrone 2 Status ========================
Version:        2.4.8
Host:           192.168.1.1 ( after boot)
Serial number:      PS721003AJ4K100674
Network id:     ardrone2_100674
Motor software:     1.43    1.43    1.43    1.43
Motor hardware:     6.0 6.0 6.0 6.0
Currently running:  Native (program.elf),
Autorun at start:   Not installed
Vision framework:   

======================== Filesystem Status ========================
Filesystem                Size      Used Available Use% Mounted on
ubi1:system              26.3M     14.1M     10.9M  56% /
tmp                      57.7M    636.0K     57.1M   1% /tmp
dev                      57.7M         0     57.7M   0% /dev
ubi0:factory              4.8M     84.0K      4.5M   2% /factory
ubi2:update              13.2M     28.0K     12.5M   0% /update
ubi2:data                53.5M     30.6M     20.2M  60% /data
make[1]: Leaving directory `/home/justin/paparazzi/sw/airborne'
make: Leaving directory`/home/justin/paparazzi'

DONE 'make -C /home/justin/paparazzi -f Makefile.ac AIRCRAFT=ardrone2  ap.upload'

We can still used the mobile app to fly it, and our simple color tracking code works running from our laptop, however gstreamer gives a simliar error when typing 'make drone', except it is ftplib.error_temp 451.

**Comment by flixr** [comment]
@OpenUAS @fvantienen any ideas?

**Comment by flixr** [comment]
@justing88 can you change the code to print the exception?
```
    except ftplib.error_temp as e:
        print("FTP UPLOAD ERROR: Uploading FAILED: Probably your ARDrone memory is full.")
        print(e)
        sys.exit()
```
and report the output? Maybe the exact error code can give some more hints...

**Comment by OpenUAS** [comment]
Will take a look.
@justing88 which PPRZ code version (it is displayed in your Paparazzi Center bottom line...) and you wrote "there is available disk space"...  how much is there?
 in your drone telnet terminal: 
 df -h

**Comment by OpenUAS** [comment]
@justing88 since I could not reproduce atm and there is no reponse for a while .. It is not that I do not want to test further, IMHO be we better then have a discussion via mailing list or or gitter.im to sort it out. Feel free to reopen the issue is you have more info so we can help to fix.
