### ISSUE TITLE
Bebop 1 GPS not working in master

### ISSUE THREAD

**Issue by dewagter** [paparazzi/paparazzi#1617]
- GPS port OK
 - GPS is configured
 - NMEA is decoded (incl PERCRV msg)

Abi message not sent or used: https://github.com/paparazzi/paparazzi/blob/master/sw/airborne/subsystems/gps/gps_nmea.c#L108

any tips?

_____

ABI_NOT_SENT (in the else)!
parse 65 GSV
GSV: "GPGSV,4,3,13,30,12,319,19,15,11,037,,26,11,174,21,13,03,005,,1*63" 
p_GSV() - 4 sentences
p_GSV() - sentence=3
p_GSV() - num_sat=13
p_GSV() - GPS 8 PRN=30 elev=12 azim=319 snr=19
p_GSV() - GPS 9 PRN=15 elev=11 azim=37 snr=0
p_GSV() - GPS 10 PRN=26 elev=11 azim=174 snr=21
p_GSV() - GPS 11 PRN=13 elev=3 azim=5 snr=0

**Comment by dewagter** [comment]
when decoding, all is filled in the gps_nmea, but the ABI function sends gps. Who should fill gps?

**Comment by kirkscheper** [comment]
I guess it should be sending GPS_nmea

Kirk

**Comment by dewagter** [comment]
gps_nmea is the wrong struct type for the ABI message. So I guess it must be copied?

**Comment by kirkscheper** [comment]
Check this:
https://github.com/paparazzi/paparazzi/blob/master/sw/airborne/subsystems/gps/gps_datalink.c

**Comment by kirkscheper** [comment]
Or send &GPS_nmea.state

Kirk

**Comment by dewagter** [comment]
@felix @kirk: Thanks

-Christophe
