### ISSUE TITLE
[NPS] Fixedwing goes to HOME mode immediately after take-off

### ISSUE THREAD

**Issue by podhrmic** [paparazzi/paparazzi#1652]
Using latest master and default configuration, Ubuntu 12.04:
![screenshot from 2016-05-04 12 59 52](https://cloud.githubusercontent.com/assets/2790461/15027327/20930654-11f8-11e6-9cf9-fed4cdc09ad1.png)

Choose Bixler with the default flightplan (versatile.xml) and target NPS, compile and Simulate. The plane takes off and then immediately goes to HOME mode, even though it is not supposed to.
![screenshot from 2016-05-04 12 58 31](https://cloud.githubusercontent.com/assets/2790461/15027366/49f52810-11f8-11e6-8c15-0d36f689cd2a.png)

It works normally in SIM.

Ideas?

And actually thinking of it, would there be some clever solution how to utilize the NPS/SIM for automated SITL checking? I.e. you test not only builds, but also the SITL performance...

**Comment by flixr** [comment]
Seems to be something introduced with #1637, not sure exactly what yet though...

**Comment by podhrmic** [comment]
Nice! Thanks for the quick response:)
