### ISSUE TITLE
GCS arg of section programs not working for Simulation session

### ISSUE THREAD

**Issue by dewagter** [paparazzi/paparazzi#1668]
This does NOT work for me.

```
  <section name="programs">
    <program name="GCS" command="sw/ground_segment/cockpit/gcs">
      <arg flag="-layout" constant="bottom_settings.xml"/>
    </program>
  </section>

```
The following DOES work (except for REPLAY and SIMULATION)

```
  <section name="sessions">
    <session name="FOO">
      <program name="GCS">
        <arg flag="-speech" />
        <arg flag="-layout"  constant="bottom_settings.xml" />
      </program>
    </session>
  </section>

```

**Comment by dewagter** [comment]
discussion started in #1600

**Comment by flixr** [comment]
The first is used if you start the GCS from the tools menu, the second if you start the session FOO

**Comment by dewagter** [comment]
Any trick to set the layout for the SIMULATION then?

-Christophe

**Comment by flixr** [comment]
I think that is currently hardcoded, but we can probably change that to use the entry with arguments from the control_panel.xml
