### ISSUE TITLE
NatNet2ivy should request version number from optitrack

### ISSUE THREAD

**Issue by kirkscheper** [paparazzi/paparazzi#1697]
The current software has hardcoded version numbers. This should be made more portable by requesting the sdk version number from natnet using a PING request.

**Comment by OpenUAS** [comment]
Some old links but still mabe useful about the dissussion with Optitrack devs
https://forums.naturalpoint.com/viewtopic.php?f=59&t=13272

**Comment by gautierhattenberger** [comment]
This should work already with latest natnet add the python tool NatNet3
