### ISSUE TITLE
Waypoint LLH not updated after geo-init

### ISSUE THREAD

**Issue by dewagter** [paparazzi/paparazzi#1710]
struct LlaCoor_i *lla = waypoint_get_lla

still provides the initial flightplan origin even after a GEO-Init

**Comment by flixr** [comment]
I guess you set the waypoint as a global one? Then it doesn't change with geo-init...
See http://docs.paparazziuav.org/latest/subsystems_2navigation_2waypoints_8h.html#a2ed9112b04893275873729d03176f490

**Comment by flixr** [comment]
See also https://github.com/paparazzi/paparazzi/pull/1065

**Comment by dewagter** [comment]
When LLH are defined: I know waypoints do not move: perfect
When XY are defined: they update nicely in the paparazzi ground station: perfect

But:

After a geo-init: the ```waypoint_get_lla``` function (e.g. called from mavlink waypoint.c) still returns the flightplan origin+xy.

**Comment by flixr** [comment]
I don't understand what you mean: if the waypoint has it's global LLA coordinates set, then it will always return that (and that equals flight plan origin + xy).

Maybe you can provide a concrete reproducible example of where it goes wrong?
