### ISSUE TITLE
[airframe generator] throw an error when a requested module doesn't exsit

### ISSUE THREAD

**Issue by kirkscheper** [paparazzi/paparazzi#1721]
Title says it all

**Comment by gautierhattenberger** [comment]
Obviously, if you ask for something that doesn't exist, it will complain. Which kind of behavior would you expect when loading an invalid module/subsystem ?

**Comment by flixr** [comment]
it seems that it currently does not complain anymore, just silents skips the invalid one...

**Comment by gautierhattenberger** [comment]
really ? If try to load a module like `bla` it just fails. Actually it fails because the module doesn't exist and it falls back to subsystem, which doesn't exist either, so make is failing.

**Comment by kirkscheper** [comment]
What I did today was <module name="cv_optickflow"\> which was a typo. It gave me no warning at all. just built and uploaded.

**Comment by gautierhattenberger** [comment]
can you provide the example airframe and paparazzi version you are using ?

**Comment by kirkscheper** [comment]
paparazzi version was a copy of master from today with the bebop 
airframe from the examples folder with the added line I mentioned.

**Comment by gautierhattenberger** [comment]
hum, actually, if you make a typo in a module from the firmware section, but not from the modules section. I'll look into this.

**Comment by flixr** [comment]
It doesn't fail if the bad module is in the `<module/>` section
