### ISSUE TITLE
datalink message for external magnetometer

### ISSUE THREAD

**Issue by bartslinger** [paparazzi/paparazzi#1756]
Adding messages is a sensitive subject, so I'd rather hear your opinions first before making a PR.

For making my lisa/s helicopter fly autonomously, I cannot use the onboard magneto.The Lisa/S had no spare pins for an additional i2c magneto. However the ESP8266, which I use for telemetry, does. I reprogrammed the ESP to read magnetometer values and put it in a PPRZ message to the Lisa/S over UART. The same ESP also reads UDP packets and transforms it to PPRZ messages on the same UART.

So what I need is:
A message in the datalink class with 3 x 16 bit integer.

This message will not be useful for anyone but me. What should I do?

**Comment by flixr** [comment]
We still have quite a few datalink message ids left (free telemetry ids are getting really scarce), I think it would be fine to add a datalink message for an external MAG.
And it could also be useful for others...
