### ISSUE TITLE
Bebop bottom camera not functioning properly

### ISSUE THREAD

**Issue by wilcoschoneveld** [paparazzi/paparazzi#1762]
Today we updated the firmware of two bebop drones (one from version 1.98, the other 2.0) to the latest 3.2.0. After updating, the bottom camera does not work as expected. We tried to isolate the issue by testing on both drones and performing a factory reset (by holding the power button for 10 sec).

The problems encountered are as follows;
- The bottom camera cannot initialize (common)
- The bottom camera runs but shows only 50% FOV (sometimes, after factory reset)
- Running ap.elf via telnet shows the following error; `Select timeout on /dev/video0`

Additional information:
- We are using the tudelft_course2016_bebop_avoider airframe, but using only the video_thread, cv_colorfilter and video_rtp_stream modules.
- The front camera works as expected, even when trying to run both camera's in parallel
- Even when the bottom camera is working somewhat (with half of the expected field of view) the video stream delay is longer than before)

**Comment by dewagter** [comment]
Probably the resolution changed. If you try to open at the wrong resolution
then you can open the video device

-Christophe

**Comment by kirkscheper** [comment]
is there any progress with this issue? It is blocking for a project we are working on.

**Comment by wilcoschoneveld** [comment]
I'm going to quickly look at the resolution setting tomorrow, i'll report back.

**Comment by fvantienen** [comment]
As I explained in my other PR with my new branch you have more settings and everything works fine.

**Comment by kirkscheper** [comment]
> everything works fine.

@fvantienen the front camera doesn't work on your PR as @wilcoschoneveld stated in that thread, has that changed since last week? If not do you have an estimate as to when will it be working?
