### ISSUE TITLE
Use new intermcu for fixedwings

### ISSUE THREAD

**Issue by flixr** [paparazzi/paparazzi#1771]
For the rotorcraft firmware @fvantienen implemented a better intermcu abstraction in subsystems/intermcu, which we should probably also use for the fixedwing firmware and get rid of the old inter_mcu.[ch].

**Comment by OpenUAS** [comment]
Offer to test and testfly it for Pixhawk and Dual LisaM setep when done

**Comment by OpenUAS** [comment]
More likely to move all FW specials over to rotorcraft bit by bit...

**Comment by gautierhattenberger** [comment]
done with #2828
