### ISSUE TITLE
ARDrone camera fails to start

### ISSUE THREAD

**Issue by dewagter** [paparazzi/paparazzi#1803]
New PIXFORMAT and CROP routine for BEBOP break the grabbing for ARDrone2 on both **front** and **bottom** camera's.

ARDrone2 camera now fails at:

```printf("[v4l2] Pixelformat not available on device %s (wanted: %d)\r\n", device_name, _pixelformat);```

the requested format is:

 ``` .format = V4L2_PIX_FMT_UYVY,```

commenting out the return null, the v4l2 then fails at CROP.

**Comment by fvantienen** [comment]
Can you print out the supported formats?
And if you also disable the crop? Prolly we can disable that if it is equal to the sensor size or something like that.
