### ISSUE TITLE
Xsens GPS is missing proper timestamp

### ISSUE THREAD

**Issue by flixr** [paparazzi/paparazzi#186]
UTC time received from the Xsens should be used to compute the GPS week and itow.

gps.week is currently always zero and gps.tow is also set to the xsens_time_stamp (which is what?)
##

**Comment by podhrmic** [comment]
This is relevant to vectornav as well. Is there a good algorithm to calculate TOW from UTM?

**Comment by flixr** [comment]
There is OCaml code to convert time in UTC to GPS tow in latlong.ml (gps_tow_from_utc)...
Don't think there is airborne code for that atm...

**Comment by gautierhattenberger** [comment]
does anyone want to work on this ? otherwise I might close this one

**Comment by gautierhattenberger** [comment]
closing for timeout
