### ISSUE TITLE
[flight plan] 'until' attribute behavior is not consitent

### ISSUE THREAD

**Issue by gautierhattenberger** [paparazzi/paparazzi#1903]
If you have `<attitude ... until="some_condition"/>`, it will generate

```
if (some_condition) NextStageAndBreak();
NavAttitude(...)
break;
```

But if you do `<circle ... until="some_condition"/>`, you will have

```
NavCircle(...)
if (some_condition) NextStageAndBreak();
break;
```

So, in the first case, if the condition is not true, the nav instruction will not be called, while with the second case, nav instructions are called at least once before changing stage.
For the first case, `heading`, `attitude` and `manual` are concerned. For the second, it's `go`, `stay`, `circle`, `eight`, `oval` and `survey`.

Which behavior should be kept ?

**Comment by dewagter** [comment]
Until should be
-do
-check if again

While should be
-check
-do
