### ISSUE TITLE
support for externally mounted mags

### ISSUE THREAD

**Issue by flixr** [paparazzi/paparazzi#197]
We should support externally mounted mags, e.g. for the case where you can't (or don't want to) use the mag on the IMU board for interference reasons.
This means 
- [x] separate ABI id for mag subscriptions in AHRS wrappers
- [ ] need to be able to set a separate MAG_TO_BODY orientation
##

**Comment by OpenUAS** [comment]
not having  a MAG to body more and more an issue with all the different supported hardware in Lab so raised level a bit

**Comment by podhrmic** [comment]
Already works on pixhawk (HMC58xx), so closing as resolved.
