### ISSUE TITLE
Incorrect variable type in ABI messages

### ISSUE THREAD

**Issue by ETitus** [paparazzi/paparazzi#1973]
The AbiSendMsgOPTICAL in opticflow_module.c sends float opticflow_result.noise_measurement, however the ABI definition of AbiSendMsgOPTICAL_FLOW handles a uint8_t instead. 

This results in loss of information when logging this quality. I expected values between 0 and 1, but only received 0s and 1s.

I came across this issue when improving the OF algorithms.

**Comment by flixr** [comment]
closed with #1974
