### ISSUE TITLE
improve NPS sim: should also handle fixedwings

### ISSUE THREAD

**Issue by flixr** [paparazzi/paparazzi#198]
The NPS sim should be slightly extended to also handle fixedwings.
The main "problem" there currently is that it also used the sim target and sim arch, which is already used for the simple ocaml sim on fixedwings.
We could make a new target for that, e.g. call it nps.

Maybe we should also start to slowly get rid of sim arch, as this is not a real arch anyway.
In case of simulated sensors these are rather specific subsystem implementations, e.g. subsystems/gps/gps_sim.[ch] and subsystems/gps/gps_sim_nps.[ch]

Also NPS just needs some more love in general...
We could probably also get rid of the fixedwing jsbsim sim at some point, as that is just a subset of nps.

**Comment by MJafarMashhadi** [comment]
Sorry to comment on such an old issue. I hope that isn't too bad.

I can't build it, the microjet makefile has an include directive for `$(CFG_SHARED)/fdm_jsbsim.makefile` which doesn't exist. I'm very new to this platform though, it might be my mistake somewhere; that's why I was hesitant to open a new issue.

I opened the Paparazzi center, loaded microjet A/C and changed the airframe to `microject_lisa_m.xml`. Selected `nps` as build target and hit Build. Here's what I got back:

```

Paparazzi version v5.15_devel-229-g3fb4ee4d5
-----------------------------------------------------------------------
#######################################
# BUILD AIRCRAFT=Microjet, TARGET nps
#######################################
make[1]: Entering directory '/home/ict520c/Documents/paparazzi'
make[1]: Nothing to be done for 'radio_ac_h'.
make[1]: Leaving directory '/home/ict520c/Documents/paparazzi'
make[1]: Entering directory '/home/ict520c/Documents/paparazzi'
make[1]: Nothing to be done for 'flight_plan_ac_h'.
make[1]: Leaving directory '/home/ict520c/Documents/paparazzi'
make[1]: Entering directory '/home/ict520c/Documents/paparazzi'
/home/ict520c/Documents/paparazzi/var/aircrafts/Microjet/Makefile.ac:410: /home/ict520c/Documents/paparazzi/conf/firmwares/subsystems/shared/fdm_jsbsim.makefile: No such file or directory
make[1]: *** No rule to make target '/home/ict520c/Documents/paparazzi/conf/firmwares/subsystems/shared/fdm_jsbsim.makefile'.  Stop.
make[1]: Leaving directory '/home/ict520c/Documents/paparazzi'
Info: module 'gps.xml' has been loaded several times for target sim, merging options
Info: module 'imu_common.xml' has been loaded several times for target nps, merging options
Info: module 'gps.xml' has been loaded several times for target nps, merging options
Info: module 'imu_common.xml' has been loaded several times for target ap, merging options
Info: module 'gps.xml' has been loaded several times for target ap, merging options
Makefile.ac:300: recipe for target 'nps.ac_h' failed
make: *** [nps.ac_h] Error 2
make: Leaving directory '/home/ict520c/Documents/paparazzi'

FAILED 'make -C /home/ict520c/Documents/paparazzi -f Makefile.ac AIRCRAFT=Microjet nps.compile' with code 2
```

What I need is some realistic flight data (sensor readings and servo outputs) from a fixed wing UAV. I don't have the hardware to actually fly one, and I couldn't find any telemetry logs (to no surprise, why should someone just randomly upload their flight logs?), so I decided to use NPS simulator as the simulation is more realistic.

**Comment by gautierhattenberger** [comment]
Can you share your airframe file ? This is now a "module" and for sure the subsystem subsystems/shared/fdm_jsbsim.makefile doesn't exist anymore

**Comment by MJafarMashhadi** [comment]
`conf/airframes/examples/microjet_lisa_m.xml`
[microjet.zip](https://github.com/paparazzi/paparazzi/files/4820369/microjet.zip)

I figured that `Bixler`, `Mentor Energy`, and `Minion_Lia` examples are fixed wing aircraft with NPS support, so I'm probably good to go with the data I need for my research; but this might be a bug or regression that needs to be looked at anyways.

I compiled v5.16, 3fb4ee4d.

**Comment by gautierhattenberger** [comment]
Sorry but I can't reproduce this error. If you have a more details about how to fail this build, open a dedicated issue for that. Thanks

**Comment by MJafarMashhadi** [comment]
Sure, thanks.

**Comment by MJafarMashhadi** [comment]
I don't know what has caused that makefile to be generated; I re-cloned and recompiled my paparazzi copy and it was all good.
