### ISSUE TITLE
Common Filter Interface/Macros/library

### ISSUE THREAD

**Issue by scdwyer** [paparazzi/paparazzi#199]
More and more sensor data may benefit from simple filtering to address issues with sensor environment and performance (noise, vibration, etc). Examples include IMUs, baros, sonar, etc.

It would be useful to have a common set of functions/structs/macros to implement a variety of different filter types, e.g.:
 - [x] [median filter] (https://github.com/paparazzi/paparazzi/blob/master/sw/airborne/filters/median_filter.h)
 - [x] low pass
 - [ ] high pass
 - [ ] notch
 - [ ] IIR
 - [ ] FIR

If a common method could be used where one simply uses a macro to define the type, size, etc of the filter, then call functions to add new raw data, run a sensor loop, get the new filtered value, get any performance metrics, etc, it would be easier to implement over a number of subsystems and drivers, and easier to keep it optimized and up to date.

Currently some imu subsystems do that directly in the driver (e.g. imu_navgo), but it would probably be nicer to pull this out and be able to specify which filter to use regardless of which IMU driver is providing the sensor data.

**Comment by gautierhattenberger** [comment]
Although it would be nice to have more basic filters, I'm not sure it makes sense to keep this issue opened.
When people need them, we can expect that they will add them.
Experience shows that simple filters are usually re-coded each time...
