### ISSUE TITLE
DSMX not working

### ISSUE THREAD

**Issue by kevindehecker** [paparazzi/paparazzi#1995]
Currently I'm not able to bind or get RC link with an externally binded DSMX. This is the case for me on a Pixracer as well as for @EwoudSmeur  with a Lisa mx, so it seems a software issue. (and @OpenUAS reported a similar problem)

DMS2 does still work.

**Comment by OpenUAS** [comment]
Note that airframe must have <define name="USE_DSMX"/>  in the spektum module section.

**Comment by podhrmic** [comment]
It would be good to add a note about this to wiki...

**Comment by flixr** [comment]
Actually this should be documented more clearly in the spektrum module xml....
http://docs.paparazziuav.org/latest/module__radio_control_spektrum.html

**Comment by kevindehecker** [comment]
We've just tried the USE_DSMX flag, but did not work. The RC is definitely 'binded', but still RC status in GCS remains NONE. Same steps with DSM2 give OK results.

**Comment by podhrmic** [comment]
Can anyone reproduce these results?

**Comment by OpenUAS** [comment]
Since we have all the TX, RX, and all autopilots and other needed hardware to retest, self assigned

**Comment by OpenUAS** [comment]
Soon™...

**Comment by gautierhattenberger** [comment]
timeout
