### ISSUE TITLE
Bebop 2 firmware v4.x.x breaks frontcam hardware encoding

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#2020]
The new Parrot release v4.0.3/v4.04/v4.05/5/4.0.6 firmware sadly made changes to the function offset in libh1enc.so library. As effect the frontcam is not working anymore.  Issue already known for a while but to be able to track it a bit better added to this list and assigned to self but work will be done by @fvantienen . More details will be added to issue

**Comment by OpenUAS** [comment]
libh1enc.so has a function change BTW compiler used by Parrot GCC: (Sourcery CodeBench Lite 2012.03-57) 4.6.3)

**Comment by OpenUAS** [comment]
Discussed with @fvantienen, has access to 4.0.6 new .so and he is busy fixing it...

**Comment by OpenUAS** [comment]
Status change since a lot of TU students depend on a fix. 
@fvantienen: any update on this?

**Comment by wv-tud** [comment]
Not a permanent fix, but I have been collecting my bebop (2) updates related to vision in `wv-tud/bebop_vision_update`, it currently just uploads an older version of `libh1enc.so` from previous FW

**Comment by gautierhattenberger** [comment]
@wv-tud @fvantienen is it still broken ? Do you have a proper fix ? If not to you want to integrate a workaround in the meantime ?

**Comment by wv-tud** [comment]
I will be making a pull request for the current fix/workaround shortly.

**Comment by gautierhattenberger** [comment]
The next stable release was planned these days, do you have something to fix this ? Thanks

**Comment by OpenUAS** [comment]
there was a "dirty fix" in the wv-tud repo, now looking a newer firmware again v4.2.1 :(

**Comment by dewagter** [comment]
This issue only should only affect hardware encoding which is not yet in master

**Comment by OpenUAS** [comment]
@wv-tud  yes we know you are very busy, congrats for the swarm Demo. It would be great if you could dive into ther PPRZ code and help us fix or merge a few things, TIA

**Comment by OpenUAS** [comment]
Some work done..

**Comment by gautierhattenberger** [comment]
timeout, reopen if needed
