### ISSUE TITLE
IRIS AutoPilot building Error

### ISSUE THREAD

**Issue by winszenYoung** [paparazzi/paparazzi#2037]
I try to flash iris. I have a problem to build. 
It is complie error output

```
CC /home/kdy/dev/paparazzi/var/aircrafts/Iris/ap/subsystems/imu/imu_px4fmu_v2.4.o
subsystems/imu/imu_px4fmu_v2.4.c: In function 'imu_px4_init':
subsystems/imu/imu_px4fmu_v2.4.c:48:54: error: 'IMU_L3G_SPI_SLAVE_IDX' undeclared (first use in this function)
   l3gd20_spi_init(&imu_px4.l3g, &IMU_PX4FMU_SPI_DEV, IMU_L3G_SPI_SLAVE_IDX);
                                                      ^
subsystems/imu/imu_px4fmu_v2.4.c:48:54: note: each undeclared identifier is reported only once for each function it appears in
subsystems/imu/imu_px4fmu_v2.4.c:51:62: error: 'IMU_LSM_SPI_SLAVE_IDX' undeclared (first use in this function)
   lsm303dlhc_spi_init(&imu_px4.lsm_acc, &IMU_PX4FMU_SPI_DEV, IMU_LSM_SPI_SLAVE_IDX, LSM_TARGET_ACC);
                                                              ^
../../conf/Makefile.stm32:210: recipe for target '/home/kdy/dev/paparazzi/var/aircrafts/Iris/ap/subsystems/imu/imu_px4fmu_v2.4.o' failed
make[1]: *** [/home/kdy/dev/paparazzi/var/aircrafts/Iris/ap/subsystems/imu/imu_px4fmu_v2.4.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/kdy/dev/paparazzi/sw/airborne'
Makefile.ac:236: recipe for target 'ap.compile' failed
make: *** [ap.compile] Error 2
```

I follow this video
https://www.youtube.com/watch?v=L18yjer438w

How do I solve this problem?

**Comment by winszenYoung** [comment]
this is output screenshot
![1](https://cloud.githubusercontent.com/assets/24709869/23939966/80e7770a-09a6-11e7-851e-fd9e05a267bb.png)
![2](https://cloud.githubusercontent.com/assets/24709869/23939968/82fdf000-09a6-11e7-8959-2e02b35c9fb1.png)

**Comment by gautierhattenberger** [comment]
You need to configure `IMU_L3G_SPI_SLAVE_IDX` in your airframe file. Not sure why there is no proper default value, I don't use the IRIS frame.
See: http://docs.paparazziuav.org/latest/module__imu_px4fmu_v2_4.html

**Comment by flixr** [comment]
This is already fixed in latest master... you are still using v5.10 where you probably need to add the define as @gautierhattenberger said.

Closing as it should work fine with master.
