### ISSUE TITLE
fix signs inside control loops to follow new conventions

### ISSUE THREAD

**Issue by gautierhattenberger** [paparazzi/paparazzi#207]
The issue #124 has fixed the signs from the user point of view, but some sign inversions are still remaining inside the control loops since they have not all been updated.

**Comment by flixr** [comment]
@dewagter should we still keep this open? I mean it works as is...

**Comment by dewagter** [comment]
no, don't keep open.

In the end I think fixedwing should go into rotorcraft so we only have 1
firmware. Only some nav functions are still missing, intermcu is now almost
in rotorcraft ...

-Christophe
