### ISSUE TITLE
Switch statement unreachable

### ISSUE THREAD

**Issue by podhrmic** [paparazzi/paparazzi#2072]
@gautierhattenberger this is what came from coverity scan:

![switch](https://user-images.githubusercontent.com/2790461/26907555-342b4f5a-4ba9-11e7-871c-7aac0fb8c24d.png)

Could you have a look at it and see if it s a false positive or not? I wasn't sure.

**Comment by gautierhattenberger** [comment]
It probably depends if `USE_STABILIZATION_RATE` is defined or not (used when setting horizontal mode), but I'm not even sure it is the problem. Unless coverity can provide more information, I don't know how to fix this. Doing rate mode with z_hold is probably a bad idea from the start anyway...

**Comment by podhrmic** [comment]
In that case Coverity probably complained that the mode cannot be reached without `USE_STABILIZATION_RATE` and I would assume that neither of the test airframes have this flag. 

I ll mark it as false positive, but on the other hand - shouldn't we remove the `RATE_Z_HOLD` mode in that case (being a bad idea)?

**Comment by podhrmic** [comment]
Closing as false positive.
