### ISSUE TITLE
actuators i2c - missing break

### ISSUE THREAD

**Issue by podhrmic** [paparazzi/paparazzi#2073]
@flixr do you think this is intentional? It is not written in the most clear style, so I am unsure without actually testing it:

![switch2](https://user-images.githubusercontent.com/2790461/26907660-05c685ac-4baa-11e7-9aa2-36d53f795afc.png)

**Comment by EwoudSmeur** [comment]
hm I agree it is not the most clear code, sorry about that...
For this specific break, I don't think it is needed as after executing case 4 he should stop anyway, whether it is this cycle or the next. I remember testing it and if I remember correctly it worked.

**Comment by gautierhattenberger** [comment]
I also don't think it is strictly necessary to have a `break` to make this work. It should probably be rewritten, on the over hand it is working and unless someone has time to clean the code and test it, I suggest to keep it this way.

**Comment by podhrmic** [comment]
OK, thanks for the feedback. I added a note there to keep a record for the future and to keep Coverity happy: https://github.com/paparazzi/paparazzi/commit/124f04fb0f7bc9f8d19f520cf4744b9b7a3bcf82
