### ISSUE TITLE
VECT3_BOUND_BOX bug

### ISSUE THREAD

**Issue by tomvand** [paparazzi/paparazzi#2091]
In [`pprz_algebra.h`](https://github.com/paparazzi/paparazzi/blob/master/sw/airborne/math/pprz_algebra.h#L230)'s VECT3_BOUND_BOX, some y's and z's on the second and third line seem to be swapped:
```c
#define VECT3_BOUND_BOX(_v, _v_min, _v_max) {       \
    if ((_v).x > (_v_max).x) (_v).x = (_v_max).x; else if ((_v).x < (_v_min).x) (_v).x = (_v_min).x; \
    if ((_v).y > (_v_max).y) (_v).y = (_v_max).y; else if ((_v).y < (_v_min).y) (_v).y = (_v_min). /*z*/; \
    if ((_v).z > (_v_max)./*y*/) (_v).z = (_v_max).z; else if ((_v).z < (_v_min).z) (_v).z = (_v_min).z; \
}
```

**Comment by podhrmic** [comment]
Thanks for spotting it @tomvand 
Indeed it was reversed, fixed with 42ff496e2cb87fe39575a4c25f393ef378b4bc4c
The reason we haven't discovered it before is probably because the bounding box is used only in `vehicle interface datalink` which might not be used at all.
