### ISSUE TITLE
cleanup replay

### ISSUE THREAD

**Issue by flixr** [paparazzi/paparazzi#21]
We have quite a few files and directories copied to var/replay and it is not quite clear what is needed for what and if it is actually needed at all.
e.g. we have basically the same files under var/replay/conf and under var/replay/var/AC_NAME/conf
So what exactly is needed for replaying everything correctly? The logs are clearly not enough, I also get some errors when replaying older files where the messages and/or server parser have changed in between.
##

**Comment by podhrmic** [comment]
Shall we close this since it is so outdated?

**Comment by flixr** [comment]
closing... can be re-opened if there are more specific things that need to be fixed/cleaned up...
