### ISSUE TITLE
missed Oval & Path implementation 

### ISSUE THREAD

**Issue by kenstobb** [paparazzi/paparazzi#2100]
I'm going to write a new flight plan editor based on python to be more visual and easier to use, So I want to use some part of existing flight plan editor which based on Ocaml, like map viewer and waypoint editor and the rest of the editor which includes blocks,failsafes,security margins,... will editable by a python application. So in order to edit waypoints and blocks individually I think procedures should be useful but some useful functions like 'Oval' & 'Path' not implemented in fp_proc.ml yet.

**Comment by OpenUAS** [comment]
Dear @kenstobb Maybe you are hard at work makeing this solution however no pull request of other code seen the isse isclosed, do not feel insulted we like your ideas, feel free to reopen
