### ISSUE TITLE
[autopilot] Rotorcraft firmware in_flight check assumes you have an accurate speed estimate

### ISSUE THREAD

**Issue by kirkscheper** [paparazzi/paparazzi#2112]
The in_flight check currently checks that the thrust setting, speed and acceleration are below certain limits. This however assumes that the vehicle has an accurate speed estimation, which is not always true. I recommend changing this to check only for thrust and accel and/or do something with the motors_on boolean.

**Comment by EwoudSmeur** [comment]
In what case would you have a bad speed estimation?

**Comment by kirkscheper** [comment]
Any passively stable, non quad, non GPS or optical flow vehicle... So
Delfly ;p

**Comment by dewagter** [comment]
Be a bit careful when pushing changes to master as this has crashed many
quads so far when wrong detections were made inflight.



-Christophe

**Comment by EwoudSmeur** [comment]
Doesn't the Delfly have a baro?

**Comment by gautierhattenberger** [comment]
The thresholds are configurable, so you can set something high enough in your airframe to disable some of the checks

**Comment by kirkscheper** [comment]
Yea of course, dumb of me.
