### ISSUE TITLE
[airframe] Configure items in firmare section included twice in Makefile.ac

### ISSUE THREAD

**Issue by kirkscheper** [paparazzi/paparazzi#2129]
When there is a 'configure' line in a module in the firmware, it is included twice in the airframe file. eg.

    <module name="stereocam">
      <configure name="STEREO_UART" value="UART2"/>
    </module>

results in 

    STEREO_UART = UART2
    STEREO_UART = UART2

in Makefile.ac.

**Comment by gautierhattenberger** [comment]
I'm currently re-writing all the generators. Even if it will take time, I'd rather not spend to much time fixing this kind of "bug".

**Comment by kirkscheper** [comment]
ok! sounds good. I just noticed it today and thought to mention it.
