### ISSUE TITLE
Multiple definition when using energy control and mission module

### ISSUE THREAD

**Issue by pgorczak** [paparazzi/paparazzi#2136]
[energy_ctrl.c] and [mission_fw_nav.c] both define `dt_navigation`, resulting in compilation errors when using both modules.

Renaming it in either of the file fixes this but I'm still trying to verify that the modes work together as intended.

[energy_ctrl.c]: https://github.com/paparazzi/paparazzi/blob/master/sw/airborne/firmwares/fixedwing/guidance/energy_ctrl.c#L289
[mission_fw_nav.c]: https://github.com/paparazzi/paparazzi/blob/master/sw/airborne/modules/mission/mission_fw_nav.c#L67

**Comment by kirkscheper** [comment]
You can also make them static (which they should be...).

Kirk
