### ISSUE TITLE
Computer vision; viewvideo.c; 'socket' shadows global declaration

### ISSUE THREAD

**Issue by lethargi** [paparazzi/paparazzi#2141]
Compiling in ap with the computer_vision module throws the warning

```modules/computer_vision/viewvideo.c:113:61: warning: declaration of 'socket' shadows a global declaration [-Wshadow]```

**Comment by gautierhattenberger** [comment]
this should be fairly easy to fix by changing the local  variable name

**Comment by lethargi** [comment]
I know. wasnt sure if I should change it as it may have been intended. Also I cannot make pull request. any guides which tell me what needs doing for me to fix this and make a pull request?

**Comment by dewagter** [comment]
- checkout a clean master
 - give it new name: git checkout -b newbranchname
 - make changes and commit
 - push to your github: git push yourremote newbranchname
 - browse to github.com and click pull request
