### ISSUE TITLE
VELOCITY_ESTIMATE ABI message requires vertical velocity

### ISSUE THREAD

**Issue by tomvand** [paparazzi/paparazzi#2144]
With the current definition of the VELOCITY_ESTIMATE ABI message it is not possible to send only a horizontal velocity estimate, the vertical velocity also has to be included. Setting the vertical velocity estimate to zero or stateGetSpeedNed_f()->z as a workaround results in incorrect behaviour. Can the message be changed to include a flag that indicates which axes are estimated, or separated into a horizontal and vertical estimate?

**Comment by gautierhattenberger** [comment]
A flag can be added similar to https://github.com/paparazzi/pprzlink/blob/master/message_definitions/v1.0/messages.xml#L674 in order to specify if horizontal and/or vertical estimate have been updated

**Comment by kirkscheper** [comment]
closed with #2161
