### ISSUE TITLE
Update Course2017 airframe to use GUIDANCE commands

### ISSUE THREAD

**Issue by dewagter** [paparazzi/paparazzi#2171]
See https://github.com/paparazzi/paparazzi/pull/2170

**Comment by OpenUAS** [comment]
@dewagter plz ask @tomvand to fix it, cannot assign him

**Comment by tomvand** [comment]
Is this the same as #2175? I'll look at that one during pprz day next week.

**Comment by gautierhattenberger** [comment]
is this still relevant ?
