### ISSUE TITLE
Lisa MX ChibiOS servo 1 doesn't output the waveform

### ISSUE THREAD

**Issue by podhrmic** [paparazzi/paparazzi#2179]
See here https://github.com/paparazzi/paparazzi/blob/master/conf/airframes/AGGIEAIR/aggieair_minion_rp3_lia.xml#L87

Probably a timer misconfiguration, as it works fine with non-chibios version. 

Mostly a ticket for myself to investigate later.

**Comment by kevindehecker** [comment]
I remember fixing that issue, but haven't got around pushing it to master (got stuck on that gcs settings to 0 problem). 
Prolly the fix is in here somewhere (all motors work with chibios)
https://github.com/kevindehecker/paparazzi/commits/cx10-dev2
