### ISSUE TITLE
Battery monitor shows inconsistent cell voltages

### ISSUE THREAD

**Issue by podhrmic** [paparazzi/paparazzi#2185]
[Battery monitor module](https://github.com/paparazzi/paparazzi/blob/master/conf/modules/battery_monitor.xml) shows fluctuating voltages.

![image uploaded from ios](https://user-images.githubusercontent.com/2790461/32866116-e95d89d4-ca1a-11e7-9717-ca1d3e9207dd.jpg)

Tested on bare-metal, Lisa MX.

Possible driver issue, making a ticket for myself

**Comment by OpenUAS** [comment]
Any chance to peek or get or make such a custom board? If the issue is not self assigned willing but IMHO  no one else can fix this but oneself. Also to little info to give some hints, e.g. which bus connected etc.

**Comment by podhrmic** [comment]
I will double check it, thanks for asking.

**Comment by podhrmic** [comment]
@OpenUAS apparently the university has some weird ideas about intellectual property, so the custom hardware is not available for release at the moment, sorry:-( I ll try to improve the comments, the code is IMHO general enough that it can be easily adapted to any other board using AD7997-8 chips.

**Comment by podhrmic** [comment]
Closing as this was apparently a hardware issue (so not a problem anymore).
