### ISSUE TITLE
Update FlighGear wiki entry

### ISSUE THREAD

**Issue by podhrmic** [paparazzi/paparazzi#2220]
to properly explain the difference between `native_gui` and the other mode. Also add a better FG launcher in the aggieair control panel.

here: https://wiki.paparazziuav.org/wiki/FlightGear

**Comment by tcunis** [comment]
Any news here?

**Comment by podhrmic** [comment]
still on my todo list

**Comment by podhrmic** [comment]
Honestly I don't remember any more what this was about. Hence closing for time-out.
