### ISSUE TITLE
Missing baro data in v5.12

### ISSUE THREAD

**Issue by HWal** [paparazzi/paparazzi#2223]
On my Lisa/M 2.0 with Aspirin 2.1, the Aspirin MS5611 baro is connected directly to Lisa/M via I2C.
I have `<configure name="LISA_M_BARO" value="BARO_MS5611_I2C"/>` in the airframe file.

This used to work in v5.10, but in v5.12 I get no baro data anymore.

I found that:
sw/airborne/boards/baro_board_ms5611_i2c.c

has the line:
#include "boards/bebop/baro_board.h

added in v5.12.

Commenting out the #include gives me baro data again.
Not sure if this is a permanent change, but is there an alternative position for this #include?

**Comment by OpenUAS** [comment]
IMHO should be something along the lines of :
```
#include "subsystems/sensors/baro.h"
#if defined(BOARD_BEBOP) || defined(BOARD_DISCO)
#include "boards/bebop/baro_board.h"
#endif
#include "peripherals/ms5611_i2c.h"
#include "mcu_periph/sys_time.h"
#ifdef BARO_LED
#include "led.h"
#endif
```
Will need to test in BB B2 and Disco (And validate LIsa/M2 with aspirin 2.1 before a Disco pull request but can take a bit since need to testfly Disco first and rather not at -5 C ;) this week...

**Comment by OpenUAS** [comment]
@podhrmic Is it thus the to backport this regression to v5.12 sonce you selfassigen? If so TIA ,if not ..ehh also fine ;-)

**Comment by podhrmic** [comment]
@OpenUAS I am honestly not sure - but I assigned myself since it looks like a straightforward fix, just haven't had time yet. So feel free to take over:-)

**Comment by OpenUAS** [comment]
OK, will do with @kirkscheper because of #1910

**Comment by HWal** [comment]
Thank you for the help!

**Comment by kirkscheper** [comment]
This should be solve in master now with #1910. Let use know if you still have any issues.

**Comment by HWal** [comment]
Thanks for the help! I will test this as soon as I can.
