### ISSUE TITLE
Spektrum RX with Spektrum serial out not working

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#2270]
![spektrumrxtest](https://user-images.githubusercontent.com/483944/40798387-38db43b2-650b-11e8-8549-9b71f9fddaa6.jpg)

v5.12 all OK, switching to master no RC anymore... Exact same hardware, just reflashed master instead of v5.12.

Using Official Spektrum RX, but have about 30+ different Receiver to try if needed. Also +5 different TX is needed.

More info can be added to this issue when needed, plz ask. 

Ongoing investigation. Will look at all (board)code, do logic analyser dump, etc. etc.

As Autopilot boards to test on we have all variants of Lisa M (v1.0, V2, v2,1, MX etc. also other AP boards when needed ) Well borrowed out the original Lisa L, but that is fine i guess ;() ...

**Comment by gautierhattenberger** [comment]
closed with #2326
