### ISSUE TITLE
Drawn shapes on GCS blocks Waypoint edit

### ISSUE THREAD

**Issue by Dennis-Wijngaarden** [paparazzi/paparazzi#2272]
When drawing shapes on the GCS using the IVY SHAPE message, the shapes appear on the foreground of the GCS. It can hide the aircraft symbol as depicted in the picture. When waypoints are located underneath these shapes, I'm not able to edit those points from the GCS. 

In my opinion, the shapes should be plotted on the background of the GCS in order to overcome those problems.

![issue_layers](https://user-images.githubusercontent.com/32736330/41582855-0da82b82-73a3-11e8-8dc0-2333b0981cbd.png)

**Comment by podhrmic** [comment]
Agreed. @gautierhattenberger what do you think?

**Comment by gautierhattenberger** [comment]
I agree shapes should be in a layer between maps and waypoints. I'll have a look.

**Comment by gautierhattenberger** [comment]
@Dennis-Wijngaarden can you test #2274 ?
