### ISSUE TITLE
XBEE_API not working in Fixedwing - LPC21

### ISSUE THREAD

**Issue by dewagter** [paparazzi/paparazzi#2284]

**Comment by dewagter** [comment]
- hardware-debugged the wait function: it works exactly as expected

**Comment by dewagter** [comment]
- hardware debugged: when sending "+++" config string, the put_bytes is called 3 times but only the first "+" is actually sent over the serial. The XBee obviously never replies.

**Comment by dewagter** [comment]
- while the XBee is being configured, there is also NO PWM so it looks like some master interrupt function is still off.

**Comment by gautierhattenberger** [comment]
This should be checked, but maybe the `xbee_init` function is called (from the `modules_init`) before the `mcu_int_enable` function. It does nothing on stm32, but for lpc it means the uart interrupts won't be called, so nothing will happen after the first character.

**Comment by dewagter** [comment]
See https://github.com/paparazzi/paparazzi/pull/2285
