### ISSUE TITLE
[Install] Missing dependencies on fresh install

### ISSUE THREAD

**Issue by kirkscheper** [paparazzi/paparazzi#2292]
After a fresh (like spanking new) install of paparazzi, start.py fails with 'Import Error: no module named pygtk'. Seems like that 'python-gtk2-dev' is not properly set as a dependency for paparazzi-dev.

**Comment by gautierhattenberger** [comment]
is it really `python-gtk2-dev` that is needed ? I don't have it and can still run `start.py`. I have `python-gtk2`, do you think it is enough to add this one ?

**Comment by gautierhattenberger** [comment]
Apparently the `python-gtk2` is installed when recommended packages are installed as well (as it is a recommended package of python-matplotlib which is recommended by paparazzi-dev). I can add it to the dependency list anyway.

**Comment by kirkscheper** [comment]
Yup, tested on a fresh install on a usb, working! Thanks
