### ISSUE TITLE
Auto-Settings related to modules/subsystems

### ISSUE THREAD

**Issue by dewagter** [paparazzi/paparazzi#23]
Nearly all settings are related to a certain subsystem or module. With the growing number of modules and subsystems (like new controllers, lot of different sensors with different settings) it becomes harder to manage settings. 

If the settings were split and "linked" to the corresponding subsystem/module they belong to, they could be auto-included making many things easier, cleaner and removing duplicate settings with only a few lines of difference.

e.g. if you include the digital_cam module, you could get the digital_cam.xml settings, and if you change from <subsystem name=attitude type=infrared> to <subsystems name=attitude type=imu> then the tuning.xml should not contain IR-neutral anymore, and when changing the controller type to airspeed, a different set of settings are needed again.

besides automatically included settings, it might be good to still allow customized personal settings.

options:
-auto-settings could either still be settings files in ./conf/settings/modules/ and ./conf/settings/firmwares/ 
-settings could be defined in the module.xml itself?
-automatic setting xml might be disabled with a flag like <subsystem name="control" nosettings="true" /> in for example finished products going to non-expert users
##

**Comment by flixr** [comment]
Update: With #1471 we are on track to start converting subsystems to modules and hence also enabling to specify settings associated with a subsystem (then module).

**Comment by podhrmic** [comment]
Since this is already taken care of, we should probably close this?

**Comment by flixr** [comment]
yeah, closing this as the subsystem->module conversion is tracked in #1475
