### ISSUE TITLE
XBee API ground station does not work without giving a channel

### ISSUE THREAD

**Issue by martinmm** [paparazzi/paparazzi#2304]
The xbee_api only works if a channel is given ('-ch 12' or '-ch 0xC' for default) when Data Link is started. Seems it was introduced with fa2f603945bd2853abf9d930fe1b175795a8da17 and guess something is wrong with

```
    match device.channel with
        None -> ()
      | Some ch -> Printf.printf "%s%!" (Xbee_transport.at_set_channel ch);
```

**Comment by gautierhattenberger** [comment]
These lines shouldn't do anything when no channel is given (None case). I have been using xbee modems for a while since this was merged without issues. Did you check the modem config to be sure that internal default value is still correct ?

**Comment by martinmm** [comment]
Yes, aircraft config is untouched and default. Tested with two ground modems and two aircraft (lpc21/stm32). It works ok if  the three lines are removed. Also works if -ch is given in Data Link and  Printf is replaced with debug output so nothing is sent to the ground modem.

**Comment by gautierhattenberger** [comment]
In the lines above, `Printf.printf` is used but it should be `fprintf o` instead. Is this correct ?
If you start link in a terminal with `PPRZ_DEBUG=x` in front, do you see the `end init xbee` debug trace ?

**Comment by martinmm** [comment]
Yes, probably I copied the wrong line from testing code. Will debug and also have a look at what is output on the serial port. Maybe some initialization is missing. Once the modem works it works always.

**Comment by martinmm** [comment]
There is no ```end_init_xbee```, the function returns if ```None``` is matched, xbee_api is then not enabled

Not sure this makes sense but works:

```
     fprintf o "%s%!" (Xbee_transport.at_set_my !my_addr);
+    begin
     match device.channel with
         None -> ()
       | Some ch ->  fprintf o "%s%!" (Xbee_transport.at_set_channel ch);
+    end;
     fprintf o "%s%!" Xbee_transport.at_api_enable;
```

**Comment by gautierhattenberger** [comment]
That was guess and the fixed is correct (and pushed to master). I wonder why my modem was working in xbee mode last week...

**Comment by martinmm** [comment]
Thanks! Maybe the modem was still in API mode from a previous run?
