### ISSUE TITLE
Suggested feature: password manager support

### ISSUE THREAD

**Issue by BarryMode** [paparazzi/paparazzi#2312]
On sites that require a login, it would be neat if the password could be pulled in from a password manager. Ex. Apple keychain, 1Password, etc. Alternatively, perhaps Paparazzi could have its own password management set up. That said, I understand this could easily become a complicated task, so feel free to shut it down :)

**Comment by podhrmic** [comment]
How does this relate to paparazzi?

**Comment by BarryMode** [comment]
This feature would make paparazzi easier to use. I'm going to guess that based on the response that you are not going to implement it, so I will go ahead and close this.
