### ISSUE TITLE
SBUS and DS-16 Tx

### ISSUE THREAD

**Issue by podhrmic** [paparazzi/paparazzi#2354]
The [DS16 Transmitter](http://www.jetimodel.com/en/katalog/Transmitters/@produkt/DS-16/) with  [rx8rPro](https://www.frsky-rc.com/product/rx8r-pro/) receiver seems to have an odd behaviour.

With ChibiOS and a bootloader on Lisa MX, when new code is uploaded, it is necessary to reboot the autopilot before using it. Otherwise the radio is lost and never connects. I suspect it has something to do with the way drivers are initialized in ChibiOS.

With a baremetal Lisa MX, the SBUS seems to work poorly - i.e. less smooth than with ChibiOS. 

It is a minor issue, because restarting an autopilot is not a big deal, but it would still be good to figure out why is it needed.

**Comment by OpenUAS** [comment]
Have a big variety of all the FrSky receivers in existence, except the PRO of rx8r , ...OK ..now just ordered one... Have no DS16 TX at hand though. PLZ a reference to airframe, channels, tx setup etc would be helpful to be able to reproduce. Will take a while to find time for this one... and receiver still need to arrive. Plz also if LBT version of Firmware is used and if your RX FW version is 180601

**Comment by OpenUAS** [comment]
The rx8rPro shipped package entered the Country, :) hope that airport distri releses it soon to have it before Christmas... btw have all TI CC25xx debuggers, HackRF etc tools at hand. Maybe related to issue #2370 ?

**Comment by podhrmic** [comment]
Imho #2370 fixes this, will have to test.

**Comment by OpenUAS** [comment]
RX just arrived... Fun to read FFC JFYI https://fccid.io/XYFN2409R/RF-Exposure-Info/RF-Exposure-report-3260693

**Comment by OpenUAS** [comment]
@podhrmic discussed with @fvantienen a fix for the fix ETA next week...

**Comment by fvantienen** [comment]
The fix is already there for ChibiOS, but it breaks it for Linux based systems. See #2370

**Comment by OpenUAS** [comment]
Merged, will retest on Lisa M and Disco

**Comment by noether** [comment]
@OpenUAS did you finally retest it?

**Comment by OpenUAS** [comment]
Yes, RX6R sbus on Disco work directly now after bootup, on https://github.com/paparazzi/paparazzi/commit/b885ff847007a37c8efca60868f83f0da97b5ca9. Lisa M and MX later..

**Comment by gautierhattenberger** [comment]
seems nobody really has time to look at this and a power cycle solves the problem, so closing this issue
