### ISSUE TITLE
Bebop 2 motors abruptly shutting down in takeoff block

### ISSUE THREAD

**Issue by jhabhargav26** [paparazzi/paparazzi#2361]
Hi! Is the shutting down of motors as soon as we enter the takeoff block a known problem? I have installed paparazzi master branch and trying to use the bebop2 example. It has bebop2_indi.xml as airframe and rotorcraft_basic.xml as flight plan. The simulation works but when I try it on with real bebop2 and optitrack it just keeps on shutting down. For passing the optitrack data as GPS, I have only added 

module name="gps" type="datalink"

instead of ublox. I am using paparazzi master branch and Bebop 2 firmware 4.7.1. The problem persists with firmware 4.2.0 and also if I fly by joystick.

Also the data from motive 2.1 is streamed in “y-up” reference and we are using Natnet.c file.

If you guys find time, could you also test it in your lab. I have been stuck with this issue for almost 2 months now.

**Comment by kirkscheper** [comment]
can you add a reference to your branch and airframe here?

**Comment by jhabhargav26** [comment]
Hi, the version is v5.13_devel-180-g2193ad3-dirty and the airframe is bebop2_indie.xml with one line changed as described before.

**Comment by kirkscheper** [comment]
Can you send me the branch you are using, not the version of paparazzi? Add a link to the branch from your repo here.

**Comment by jhabhargav26** [comment]
sorry. It is the master branch which I cloned from here https://github.com/paparazzi/paparazzi.

**Comment by kirkscheper** [comment]
Still not really what I want. I would like to look at the exact code you have on the bebop. Can you push your code to your fork of paparazzi to a branch of your choosing and send a link to that code?

**Comment by jhabhargav26** [comment]
I am away from my lab for next 2 weeks. I will do that once I return. For now I can tell that the code is identical to the main paparazzi master branch except that one line changed about the GPS module.

**Comment by kirkscheper** [comment]
Which conf are you using?

**Comment by kirkscheper** [comment]
No worries. When you start paparazzi with ./start you have a couple options, the one at the top is the configuration you will launch the paparazzi center with. This will define which airframes are displayed and what telemetry and settings combination to use with each airframe.

There are multiple airframes for the bebop 2, so I need to know which one you are using.

**Comment by OpenUAS** [comment]
@jhabhargav26  The directory $PPRZ/var/generated should contain the config data of the AC you used while testing, might come in handy for debug. 

Can retest for you but than best to have info @kirkscheper ask

Hint: a faster takeo with a not so good batter, dips the voltage unter the LowBat voltage, an exception in you flightplan could trigger a land here. 

A log file of a flight will tell you almost all...

**Comment by jhabhargav26** [comment]
Hi, Please find attached the log file. Also i have attached the whole var folder.
[var.zip](https://github.com/paparazzi/paparazzi/files/2652398/var.zip)
[18_12_06__10_41_44.log](https://github.com/paparazzi/paparazzi/files/2652399/18_12_06__10_41_44.log)

**Comment by kirkscheper** [comment]
Thanks, looks like this is a but older version of pprz, have you tried master? Also, in this log, your battery wasn't close to full, What @OpenUAS could very well be what's happening to you. It seems like pprz crashed on take off. Is the bebop still on after the motors stop (is the light still on)?

**Comment by jhabhargav26** [comment]
yes, i tried with master version too and still the problem persisted. In past, we have also tried with full battery and it didn't help. 
After the crash, the bebop gets switched off and it doesn't switch on with power button. We have to remove the battery and put it back to get it on.

**Comment by kirkscheper** [comment]
Doesn't sound like a pprz issue honestly. the software should not cause the board to shutdown like this. Do you have access to a different bebop2 to test? Does it work with the freeflight app?

**Comment by kirkscheper** [comment]
What firmware version is on the bebop?

**Comment by jhabhargav26** [comment]
It's 4.7.1

**Comment by kirkscheper** [comment]
So, I took a look at this again and there are a few things.

First, the airframe you are using is not meant for flying autonomously in a motion capture / indoor environment. I recommend you look at the an example from /conf/airframes/tudelft/bebop_optitrack.xml.

Note the defines: USE_MAGNETOMETER, AHRS_USE_GPS_HEADING, HEADING_UPDATE_GPS_MIN_SPEED, USE_GPS_ALT, VFF_R_GPS (VFF_R_GPS_SPEED).

I will try to refactor some of the module things that these have reasonable defaults when using datalink gps but all these have to be updated to have a good flight.

Additionally, the flightplan used is intended for outdoor flight where the security height is 2m, ground alt is 147 m and the flight plan alt is 152 m. This would all create a few issues if you are flying inside.

As to why when you manually fly in attitude mode with a joystick it doesn't work, i can't help you. Did multiple flights today with master with no issues.

**Comment by OpenUAS** [comment]
FYI We've tested Bebop 2 4.7.1 only on Motive 1.1x not the motive 2.1...are you using natnet v3?

**Comment by OpenUAS** [comment]
@jhabhargav26 Any update on this?

**Comment by jhabhargav26** [comment]
Sorry for the late reply. Yes we are using Motive 2.1 with Natnet 3.0. 
But in the GCS we could see the right coordinates of the bebop, so I don’t know if it is a problem.

**Comment by OpenUAS** [comment]
Will close for now @jhabhargav26 feel free to reopen  the issue if you find time to retest.
