### ISSUE TITLE
Upgrade ChibiOS to get RNG working

### ISSUE THREAD

**Issue by podhrmic** [paparazzi/paparazzi#2369]
Currently the random number generator (RNG) is enabled only for bare-metal STM32 boards. ChibiOS 18.2.2 doesn't have drivers for RNG, but the latest master does.

Having a RNG is necessary for any kind of crypto, such as secure pprzlink. I want to do a major overhaul of the encrypted telemetry (using more Rust from #2355) so it would  be nice to have ChibiOS with RNG.

I tried to do a quick update to see what it takes, but I couldn't get the master version of ChibiOS to work, since its build system is different than18.2.2. It probably needs someone who is more familiar with Makefiles.

@gautierhattenberger you did ChibiOS upgrade before, is this something you would be willing to look at?

I am not in rush for this (maybe we can wait for next stable ChibiOS release?), but wanted to mention it.

**Comment by gautierhattenberger** [comment]
closed with #2646
