### ISSUE TITLE
Airframes TUDelft configuration not up to date

### ISSUE THREAD

**Issue by kirkscheper** [paparazzi/paparazzi#2375]
The airframes in the TUDelft folder are a bit difficult to navigate, some have quite redundant info with little documentation. We need to update this.

**Comment by OpenUAS** [comment]
WIP

**Comment by gautierhattenberger** [comment]
can someone handle this or close the issue ?

**Comment by gautierhattenberger** [comment]
I'm closing this. I'll make a big cleaning after next release anyway.
