### ISSUE TITLE
Airframes in examples not up to date

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#2376]
The airframes in the example some have quite redundant info with little documentation. We need to update this.

**Comment by OpenUAS** [comment]
So after PR  #2478 time to spend Christmas with this one...

**Comment by gautierhattenberger** [comment]
\all feel free to fix / clean your airframe configs
https://semaphoreci.com/paparazziuav/paparazzi/branches/master/builds/3192

**Comment by gautierhattenberger** [comment]
timeout
