### ISSUE TITLE
Bebop airframes in master get 'Segmentation fault (core dumped)' with sonar

### ISSUE THREAD

**Issue by ls90911** [paparazzi/paparazzi#2378]
I pulled the latest master branch and tested Bebop airframes in tudelft/conf.xml.  I found that if I used the airframes which have sonar,for example Bebop_default,  then the system will crash with the information 'Segmentation fault (core dumped)'. 

I used printf() to debug and found that the codes ended up at line 144, 

spi_submit(&spi0, &sonar_bebop_spi_t);

Currently I am at the commit ' mark as v5.15 devel until next release'. 

Thanks!

**Comment by gautierhattenberger** [comment]
do you mean that it is working if the sonar is not activated ?

**Comment by ls90911** [comment]
> do you mean that it is working if the sonar is not activated ?

Yes. If I comment out <module name="sonar_bebop"/>, it works.

**Comment by kirkscheper** [comment]
@ls90911 can you test if  #2379 fixes your issue?

**Comment by ls90911** [comment]
> @ls90911 can you test if #2379 fixes your issue?

Yes, now it works! Thanks!

**Comment by kirkscheper** [comment]
Fix merged to master
