### ISSUE TITLE
Vertical reference is wrong in guided mode

### ISSUE THREAD

**Issue by ls90911** [paparazzi/paparazzi#2410]
In my module, I keep call autopilot_guided_goto_ned(0.0,0.0,-1.5,0) with fixed frequency. However, the reference is not kept at -1.5. You can find the log here.
![Screenshot from 2019-03-26 10-45-34](https://user-images.githubusercontent.com/16644673/54998956-9cdc0400-4fcf-11e9-8a0e-3464396bcc64.png)

The problem might be that in **guidance_v_set_guided_z(float z)**, there are two lines

guidance_v_z_sum_err = 0; 
GuidanceVSetRef(stateGetPositionNed_i()->z, stateGetSpeedNed_i()->z, 0);

which update the reference based on current altitude.

**Comment by OpenUAS** [comment]
@ls90911 Plz check if it is still an issue in latest master of today I could not reproduce it.

**Comment by dewagter** [comment]
@OpenUAS bug is still there:

https://github.com/paparazzi/paparazzi/blob/50f574d4581d027f5edec207f106e9d81e4c2ded/sw/airborne/firmwares/rotorcraft/guidance/guidance_v.c#L565

This resets the reference to the current altitude every time you set the guided_z. So if you do that at 512Hz the drone is constantly at the perfect altitude and allowed to drift as much as it wants. If you **guided_v_set_guided_z** slower, then the slower, the better the altitude...

**Comment by gautierhattenberger** [comment]
I can reproduce it today as well but didn't have time to try possible correction. Because the previous line is also a problem (setting integrator to zero). If I'm not wrong, we should just remove these two lines and also one in `set_guided_vz function`, then the ref should be normally updated from the `guided_run` function. But better try it before...

**Comment by dewagter** [comment]
Yes I think they should only be in the on_enter function (certainly not called at 512Hz) and be removed in all set functions.

**Comment by ls90911** [comment]
I have fixed it in my branch. Will send a PR soon.
