### ISSUE TITLE
Fixedwing Safety Modes

### ISSUE THREAD

**Issue by dewagter** [paparazzi/paparazzi#2415]
- TOO_FAR_FROM_HOME with RC (disco) -> NO HOME 
      - (1.5*too far, throttle off works)
      - microjet simulator seems works
 - HOME mode throttle: 100% (disco) after boot (88% in sim) and failsafe-throttle after GPS_ERROR

**Comment by gautierhattenberger** [comment]
- RC modes are not affected by too_far_from home, only NAV: https://github.com/paparazzi/paparazzi/blob/master/sw/airborne/firmwares/fixedwing/autopilot_static.c#L128

- can it be a bug in the linux PWM driver ? how do you enter HOME mode at boot ?

**Comment by gautierhattenberger** [comment]
- First point is not a bug at the moment, but should however be considered as the new European regulation is needing it -> make a dedicated Issue/PR for that
- If not more information on second point, I'll close this one

**Comment by gautierhattenberger** [comment]
timeout
