### ISSUE TITLE
Semaphore CI is broken

### ISSUE THREAD

**Issue by fvantienen** [paparazzi/paparazzi#2425]
Semaphore CI is failing with this error:
```
CC /home/pprz/paparazzi/var/aircrafts/Vivify/fbw/arch/stm32/mcu_periph/can_arch.o
link_mcu_can.c: In function 'link_mcu_periodic_task':
link_mcu_can.c:152:57: error: expected ';' before ')' token
   intermcu_tx_buff[4] = (uint8_t)(vsupply & 0xff00) >> 8);
```

Next tot that a lot of other warnings are shown which could be easily solved in Semaphore CI, see https://semaphoreci.com/paparazziuav/paparazzi/branches/master/builds/2789.

**Comment by gautierhattenberger** [comment]
fixed with 7cb51a8c219404579b16851434878aa49aae9462
