### ISSUE TITLE
EKF2  tilt_ekf documentation lacking

### ISSUE THREAD

**Issue by somiyajena98** [paparazzi/paparazzi#2456]
Unable to find the document explaining how the c code of ekf has been implemented in tilt_ekf.c and tilt_fast_ekf.c 
Can you please share the document ?

**Comment by OpenUAS** [comment]
You might have more luck to get an answer on https://gitter.im/paparazzi/discuss or the mailing list as this is an issue tracker not a forum. If you found what you need, and  enhanced some docs please feel free to submit a Pull request TIA
