### ISSUE TITLE
Inability to change position resolution 

### ISSUE THREAD

**Issue by danielwillemsen** [paparazzi/paparazzi#2457]
When using ins_int for slow indoor flight, the default position resolution ( [INT32_POS_FRAC](https://github.com/paparazzi/paparazzi/blob/bb35c16de89b01ac0b34e2a8ae09de8660db59ee/sw/airborne/math/pprz_algebra_int.h) ), is not enough to detect all relevant motion, this can result in position drift.

Changing the position resolution is not trivial as many other locations still have this hard-coded (one example is the horizontal guidance PID).

This makes ins_int without HFF less usable for slow indoor flight.

Related: #1895

**Comment by OpenUAS** [comment]
Thx, great find! Since there is no further issue described to act upon, will close. Feel free to reopen and add additional info, defect find etc.
