### ISSUE TITLE
Bebop (1 or 2) parameters

### ISSUE THREAD

**Issue by Black-Ali** [paparazzi/paparazzi#2556]
Hello, 
Hope you are all doing well :slightly_smiling_face:

Would it be possible to find someone who can share the Bebop (1 or 2) physical parameters? In fact, I am designing a controller and I was looking for these parameters in order to simulate my controller on it using MATLAB & Simulink. Unfortunately, I found nothing on the Internet. 

By physical parameters, I mean mass, arm lengths, thrust coefficient, drag coefficient, inertia matrix, rotor's inertia, and any other useful parameter.

Any other quadrotors parameters would be of great help too! 

Thanks in advance!

**Comment by gautierhattenberger** [comment]
Hello,
I think the best is to start from the simulation file here: https://github.com/paparazzi/paparazzi/blob/master/conf/simulator/jsbsim/aircraft/bebop.xml
You will find most of the information you need.
