### ISSUE TITLE
BUG: [needs triage] Microjet in NPS stuck in land stage during the landing

### ISSUE THREAD

**Issue by MJafarMashhadi** [paparazzi/paparazzi#2561]
- [x] confirmed it exists on the latest stable release (5.16 3fb4ee4d5)
- [ ] confirmed it exists on latest version on master (03350bb)

I am simulating Microjet with `microjet_lisa_m` airframe on the `basic` flight plan. When I am using the old `sim` simulator and jump to 'land right' ('or land left') block it starts descending on a spiral route until it reaches AF at a certain altitude then continues a straight and stable glide slope until flaring and touching down. However, when I am using `nps` simulator, after descent it keeps circling above AF at a fixed low altitude and doesn't continue on `final` and `flare` blocks. If I double click 'final' to force it to continue landing procedure it works fine though.

Is it a bug or something that I am doing wrong?

**Comment by gautierhattenberger** [comment]
This is most likely a bad tuning of the airframe for the NPS model. This line https://github.com/paparazzi/paparazzi/blob/master/conf/flight_plans/basic.xml#L76 is telling that it should switch to `final` block if the direction of flight is correct and the altitude in a range of 10 meters around the altitude of `AF`. If you are too low or too high it will keep circling. You can try to adjust the nominal cruise throttle in the settings to have a better altitude tracking.
