### ISSUE TITLE
GDB not found when using Prefix with multiple crosscompilers

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#2589]
When using multiple toolchains e.g. a specific one for ARDrone2 where the toolchain is not in the path no GDB found

For example (with OS Busybox on ARDrone2) your stuck with a toolchain for crosscompiling because of libc :( in your airframe one can set:
```xml
<!-- If your cross compiler resides somewhere else, change this line an point to where it is -->
<configure name="PREFIX" value="/opt/arm-2012.03/bin/arm-none-linux-gnueabi"/>

**Comment by gautierhattenberger** [comment]
It is probably possible to handle that with something like
```
GDB = $(shell which $(PREFIX)-gdb)
ifeq ($(GDB),)
GDB = $(shell which gdb-multiarch)
endif
```
But where is it exactly failing with linux-based compilation ? GDB should not be used for compilation or flashing. Are you really doing remote debugging ?

**Comment by OpenUAS** [comment]
Yes, for optical flow
