### ISSUE TITLE
fatal error: nav_cube.h: No such file or directory

### ISSUE THREAD

**Issue by jburns11** [paparazzi/paparazzi#2608]
Hello all,

I ran into an error when trying to use nav_cube.h. If you insert either of the lines 
module name="nav" type="cube"
or
module name="nav_cube"
into an aircraft file, you will get an error from settings.h. This file tries to include nav_cube.h, but from what I understand it should be trying to include nav/nav_cube.h.

It seems like when settings.h is being generated, the directory tags are not being correctly parsed from the aircraft file. For instance, when I include the "nav_smooth" module in the aircraft, the import statement is nav/nav_smooth.h.

Best,
Jack

**Comment by gautierhattenberger** [comment]
You're right, there is a mistake in the module xml file. Every `module="nav_cube"` in the `dl_setting` nodes should be `module="nav/nav_cube"`.
This is a pain for now, but want to fix this someday so that these includes are automatic. A pull request to fix it would be greatly appreciated :)

**Comment by jburns11** [comment]
Created a PR for this! Guess this issue can be closed!
