### ISSUE TITLE
HGT files not downloaded anymore

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#2642]
A directory server change on https://dds.cr.usgs.gov/ make current OCAML code not download SRTM anymore
continents are now in subdir e.g. https://dds.cr.usgs.gov/srtm/version2_1/SRTM3/Australia/
A way to change the code could be try to download from first in a list ,if download not possible try next of list since the list is small easier to code and take less space than a lookup table which file belon to which directory... an likly just as fast...

Africa/
Australia/
Eurasia/
Islands/
North_America/
South_America/

OCAML Fu is missing at the moment, else would have made PR, for now for the needy ones with HD space left run this oneliner for your continent change the last part..

`wget -e robots=off --cut-dirs=3 --user-agent=Mozilla/5.0 --reject="index.html*" --no-parent --recursive --relative --level=1 --no-directories https://dds.cr.usgs.gov/srtm/version2_1/SRTM3/Eurasia`

**Comment by gautierhattenberger** [comment]
I can't access link above without a login

**Comment by dewagter** [comment]
What about using the ESA server: everything in a single folder.
 - http://step.esa.int/auxdata/dem/SRTMGL1/

**Comment by gautierhattenberger** [comment]
I like the idea :) thanks
