### ISSUE TITLE
Timer12 for chibios not available

### ISSUE THREAD

**Issue by Dennis-Wijngaarden** [paparazzi/paparazzi#2643]
Chibios needs to be updated in order to make timer12 available. Timer12 is for example needed to control the PWM signal for SERVO 7 and SERVO8 on the px4fmu_5.0_chibios board.

**Comment by gautierhattenberger** [comment]
This was planned but without a specific deadline. I will try to push this up in the TODO list. Since we will jump at least 1 or 2 ChibiOS stable versions, some API are likely to change, so it can take some time to fix everything.

**Comment by gautierhattenberger** [comment]
ChibiOS have been update to 20.3
