### ISSUE TITLE
INS_SONAR_UPDATE_ON_AGL unused?

### ISSUE THREAD

**Issue by tomvand** [paparazzi/paparazzi#2671]
While trying to find out the function of the `INS_SONAR_UPDATE_ON_AGL` define, I noticed that its value is stored in `ins_int.update_on_agl` [ins_int.c](https://github.com/paparazzi/paparazzi/blob/182c931e6b851c2251a11ee90765b6598aa5d972/sw/airborne/subsystems/ins/ins_int.c#L221) but that neither this field nor the define are ever used again. Should this setting be removed?

**Comment by gautierhattenberger** [comment]
It seems it was left after https://github.com/paparazzi/paparazzi/pull/1910, but can be probably removed
