### ISSUE TITLE
LDFLAGS order reversed

### ISSUE THREAD

**Issue by tomvand** [paparazzi/paparazzi#2673]
Hi, the current version of paparazzi seems to reverse the order of the LDFLAGS, which are order-dependent and this causes problems when linking multiple dependencies such as in the [cv_opencvdemo module](https://github.com/paparazzi/paparazzi/blob/master/conf/modules/cv_opencvdemo.xml). This problem did not occur during last year's tu delft pprz course, so apparently something has changed in the meantime.

**Comment by gautierhattenberger** [comment]
Do you have an idea since when you have this problem ?

**Comment by tomvand** [comment]
No. I only discovered this problem today, while I haven't used this module (or anything else with complex ldflags) since the course one year ago. But I realize that's quite a large timespan...

**Comment by gautierhattenberger** [comment]
It is possible that the final order is currently reversed compared to the original order in module XML. Can you check that ?

**Comment by tomvand** [comment]
Sorry for not responding, I was ill. Thanks for the fix!
