### ISSUE TITLE
Remove static sectors in V6.0

### ISSUE THREAD

**Issue by Fabien-B** [paparazzi/paparazzi#2677]
I propose to remove static sectors in the next major release (V6.0)
IMO, the added complexity does not worth the computing time saved, especially on "recent" microcontrollers like STM32.

I propose to make all sectors dynamic, and to remove the `type` attribute in the `sector` node of the flight plans.

Does anyone wants to keep static sectors, and if so, can you explain why ?

**Comment by fvantienen** [comment]
Since #2701 is merged this can be closed
