### ISSUE TITLE
Suppressing all telemetry

### ISSUE THREAD

**Issue by blutack** [paparazzi/paparazzi#271]
I've also got a bunch of commits which allow a complete suppression of telemetry, and in turn the use of the xbee868 reset module. 
Would they be something you'd want to merge?
##

**Comment by flixr** [comment]
@gautierhattenberger is that still the case? How do you disable all telemetry without removing the complete telemetry subsystem?
We should try to add an option to do this during runtime now as well...

**Comment by OpenUAS** [comment]
Stale for a long time...
