### ISSUE TITLE
GCS waypoints too small to select on HDPI screens

### ISSUE THREAD

**Issue by EwoudSmeur** [paparazzi/paparazzi#2757]
On higher resolution screens the waypoints become very small and hard to select/drag, and the drone icon is also so small that its heading is not really visible. Can we make this depend on the screen resolution or the Ubuntu display 'scale' parameter?

**Comment by gautierhattenberger** [comment]
This is a big effort for something that is using a deprecated library (gtk2). We are now working on a new GCS https://github.com/Fabien-B/PprzGCS and if possible don't change things in the old one.

**Comment by EwoudSmeur** [comment]
Very cool, I just installed it and it has a completely different look and feel! I'll be using this GCS for the coming flight tests. Would you like me to report any issues I encounter? e.g. pinch to zoom works on my touchpad, but not on the touchscreen :)

**Comment by gautierhattenberger** [comment]
Of course, don't hesitate to report any issue and even wished features, we will consider that.

**Comment by Fabien-B** [comment]
@EwoudSmeur I implemented multitouch support in latest release! Pinch to zoom and pan.
If you have further issues/whished features, please report them here: https://github.com/Fabien-B/PprzGCS/issues

**Comment by EwoudSmeur** [comment]
That is so cool, thank you! 😍
I'll let you know when I find something!

**Comment by Fabien-B** [comment]
I am curious: did you install it source sources or did you used the .deb? On what OS?
