### ISSUE TITLE
No telemetry type transparent_usb on ChiBios

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#2784]
To move frowart using ChiBios and still be able to get messages without any telemetry device, the 
`<module name="telemetry" type="transparent_usb"/>`

Would be very beneficial to have. BareMetal has this option there is no option yet for Chibios.

**Comment by OpenUAS** [comment]
This old post could help making it a reality http://vedder.se/2012/07/usb-serial-on-stm32f4/

**Comment by Fabien-B** [comment]
Implemented in #2878
