### ISSUE TITLE
RM3100 magnetometer module frequency doesn't benefit from sensor's high data rate

### ISSUE THREAD

**Issue by matteobarbera** [paparazzi/paparazzi#2788]
Together with @OpenUAS, while investigating #2781, we saw that the rm3100 module only polls the sensor at the 60Hz periodic frequency defined in the XML https://github.com/paparazzi/paparazzi/blob/da5b5277958126862a5bc089e224dfef77514ac4/conf/modules/mag_rm3100.xml#L33

One of the advantages of the RM3100 is that its data rate goes up to 600Hz, and the data rate can be defined in the airframe with the DATA_RATE setting, but unless the user is aware that they have to change the module frequency too, all the benefits of increasing the sensor frequency are lost.

I thought at the beginning that setting it by default to a high periodic frequency would improve the situation, perhaps even not specifying a frequency in the module XML and letting it run at max frequency. However, we saw that when the data rate is lower than the module frequency there are spikes in the data coming from the sensor, so if a user sets it to a lower data rate than they would also encounter problems.

I would propose either:

- more detailed documentation in the module files
- find a way to programmatically change the module frequency with the data rate
- issue a warning to the user (during compilation time?) if the settings could cause issues. 

With the last two points I don't know if it is possible to obtain the periodic module frequency as a variable, and if it is at what stage of compilation.

**Comment by OpenUAS** [comment]
@gautierhattenberger Thanks for the elaborate remarks, very nice! As soon as @matteobarbera is available again will fix and testfly together

As stideremark @matteobarbera  IMHO rather go for prescaling computed at compile time for more deterministic behavior.
