### ISSUE TITLE
speed up execution time of cv_opticflow.xml

### ISSUE THREAD

**Issue by pcampolucci** [paparazzi/paparazzi#2824]
A recent look at the Paparazzi optical flow module `cv_opticflow.xml` highlighted several bottlenecks that were proven to slow down dramatically the processing speed of the module. These are:

1. the `image_to_grayscale()` operation in the `calc_fast9_lukas_kanade()` function from `opticalflow_calculator.c`
2. the convolution operation to generate the pyramid in `pyramid_next_level()` from the `image.c` script

We have already tried (together with @matteobarbera), change the kernel for the convolution and separate the operation in a vertical and horizontal convolution, but given the size of the kernel this did not speed up enough. The possible solutions would be:

1. remove the `image_to_grayscale()` operation by adapting the optical flow functions (such as `pyramid_next_level()` and `image_subpixel_window()`), such as the pyramid one, to select only the Y channel of the original image. 
2. find a better convolution method (maybe FFT?) 
3. In the case use for Bebop, modify the MT9 camera driver to send directly grayscale images to the optical flow module
4. In the case of the Bebop, use a compiler designed for the Bebop's processor

optical flow wiki page: https://wiki.paparazziuav.org/wiki/Optical_flow
optical flow method literature: http://robots.stanford.edu/cs223b04/algo_tracking.pdf

**Comment by OpenUAS** [comment]
Since #2825 is merged this item contains advice, but not something to fix anymore. Not that the 2,3,4 hints are not useful, they are, but they are not actionable for this issue ATM, therefore closed so to focus on other issue.
