### ISSUE TITLE
Algebra function arguments not constant

### ISSUE THREAD

**Issue by fvantienen** [paparazzi/paparazzi#2884]
Currently there are some algebra functions where the arguments aren't constant. This means that if you use the same variable as input and output it goes wrong.
Either we need to copy the inputs, or maybe create a test that searches for these problems in the code.

For example a bug here:
https://github.com/paparazzi/paparazzi/blob/master/sw/airborne/modules/ahrs/ahrs_float_invariant_wrapper.c#L230
(This bug will eventually be fixed with #2883)

**Comment by OpenUAS** [comment]
@fvantienen stated "(This bug will eventually be fixed with https://github.com/paparazzi/paparazzi/pull/2883)"  and issue #2883 is closed, can this issue be closed as well?
