### ISSUE TITLE
Rotorcraft NavGlide altitude calculation bug

### ISSUE THREAD

**Issue by celarco** [paparazzi/paparazzi#2906]
When experimenting with flight plan **go function**, specially **glide vertical mode**, I came across a little bug in rotorcraft navigation routines which could lead to unexpected behavior. 

The exact routine I used in flight plan is:
`<go from="S1" hmode="route" wp="S2" vmode ="glide"/>`

The bug happens when:  **(altitude of WP_S1 > altitude of WP_S2)**.

 I traced the bug which is related to:
https://github.com/paparazzi/paparazzi/blob/7b1d2ccb5c4e88f7402e38e3ee033dfd9cc57dd4/sw/airborne/firmwares/rotorcraft/navigation.h#L308

The exact problem is that all the variables in the line above are of type int32_t except **nav_leg_length** which is of type uint32_t. 

When **diff_alt < 0** , the result of this calculation overflows and the result target altitude becomes an overflowed number, leading to unexpected flight behavior.

I replaced that line with this, casting nav_leg_length to int32_t and this issue was fixed quickly:

`int32_t alt = start_alt + ((diff_alt * nav_leg_progress) / (int32_t)nav_leg_length); `
  
I am not sure whether this is the ideal fix for this issue or not. I use the latest master version : [b8647d7](https://github.com/paparazzi/paparazzi/commit/b8647d7d7f29fa51544d6cc4cbc5b20cfb4a4643)

**Comment by gautierhattenberger** [comment]
Thank you @celarco for reporting this bug. You can make a pull request to integrate this correction. Otherwise, it will be done soon with other small corrections.
