### ISSUE TITLE
Issues compiling NPS on Ubuntu 22.04

### ISSUE THREAD

**Issue by jesusBV20** [paparazzi/paparazzi#2932]
I'm testing on Ubuntu 22.04 the changes made by @Fabien-B in #2922 and I experienced a problem. Since I believe it is not directly related to the changes he has made in this PR, I decided to open this issue.

When I try to compile any airframe with NPS as target, the compiler drops some multiple-definition errors like this:

/usr/bin/ld: 
/home/ubuntu-22/Workspace/paparazzi/var/aircrafts/MYAC/nps/nps/nps_ivy.o:
/home/ubuntu-22/Workspace/paparazzi/sw/simulator/nps/nps_main.h:28: 
multiple definition of `fdm_mutex'; 
/home/ubuntu-22/Workspace/paparazzi/var/aircrafts/MYAC/nps/nps/nps_flightgear.o:
/home/ubuntu-22/Workspace/paparazzi/sw/simulator/nps/nps_main.h:28: 
first defined here

Could It be related to a compiler flag?

**Comment by gautierhattenberger** [comment]
I think it is a real bug, the fdm_mutex is not an extern variable. Not sure why it was compiling (or even working). Maybe the compiler of 22.04 is more strict than before.
I will fix that.

**Comment by gautierhattenberger** [comment]
@jesusBV20 you can check with #2933
