### ISSUE TITLE
[tests] Modules ocamlc missing

### ISSUE THREAD

**Issue by fvantienen** [paparazzi/paparazzi#3096]
While compiling test modules the ocaml library isn't included.
I'm missing files like `caml/mlvalues.h` which should have been added by sth like `-I $(shell $(OCAMLC) -where)`. I don't know how to add this properly to the `test_modules.py`, maybe @gautierhattenberger or @Fabien-B has an idea?

**Comment by gautierhattenberger** [comment]
Do you have an example of module that fails because of ocaml ?
