### ISSUE TITLE
Simulator does not start with `IMU_ACCEL_`

### ISSUE THREAD

**Issue by dewagter** [paparazzi/paparazzi#3135]

**Comment by gautierhattenberger** [comment]
Do you have more details ??

**Comment by dewagter** [comment]
- when the airframe file contains ```<define name="IMU_ACCEL_CALIB"``` with 3 sensors, NPS does not align (IMU_ALIGN remains red in GCS). If you remove any of the 3 it aligns and simulates well.
 - e.g. ```tudelft/conf.xml``` with airframe e.g. ```RotatingWingV3d``` target ```NPS```: the IMU does not align in simulation.

**Comment by dewagter** [comment]
@fvantienen thinks the max is 3 IMU's but NPS adds one so 4 is too much.
