### ISSUE TITLE
Dependency on INDI. Should be made indpendent

### ISSUE THREAD

**Issue by tmldeponti** [paparazzi/paparazzi#3179]
https://github.com/paparazzi/paparazzi/blob/7b54c09acc82b15a583150cf27b2c9c88c73f6fe/sw/airborne/modules/rot_wing_drone/wing_rotation_controller_servo.c#L138C3-L138C49

look at how i fixed it:
rw3c_master
46cd43b31537f2f0b1a085934fb3bde5a2d8a396

**Comment by tmldeponti** [comment]
PR opened

**Comment by dewagter** [comment]
see PR
