### ISSUE TITLE
SPI slave mode for STM32

### ISSUE THREAD

**Issue by flixr** [paparazzi/paparazzi#326]
Add a proper implementation of SPI slave mode for STM32x.

The current implementation of SPI slave mode is very basic, i.e. only works correctly if input and ouput have the same length.

**Comment by Fab7c4** [comment]
I want to join development on #326. Can anybody confirm that #500 is giving the expected results and is in a working state. I tested the module with a signal generator as input for the clock and tried to decode the bytes on an oscilloscope with logic analyzer feature. I saw the correct clock and also some signal on MISO if SS was low. And no signal when SS was high. But it does not respresent the content in the testbuffers.

**Comment by flixr** [comment]
I haven't tested this so far, but maybe @dirkdokter can help out here as he wrote that basic implementation?

**Comment by flixr** [comment]
It looks suspicious that the dma is not enabled again in process_slave_rx_dma_interrupt though...

**Comment by Fab7c4** [comment]
I have to correct my post. The slave mode does work with the lisa/m, even if i could not decode it directly with the oscilloscope the signal plots made completely sense after some testing. I will dig a little bit more into the code written and will try to make it all more universal to use. When I have some results you hear from me.

**Comment by dirkdokter** [comment]
#500 was developed for interfacing with a Gumstix board. It was tested on a Lisa/M, and did gave the expected results. I think @hannwoei has been using this driver.

**Comment by dewagter** [comment]
https://github.com/kirkscheper/paparazzi/commits/bluegiga is now using this driver on Lisa-s

**Comment by kirkscheper** [comment]
@flixr is this fixed with #1371. If not can you give a short description what you want and I can take a look at this and test with the Lisa/s w/ bluetooth on spi slave.

**Comment by flixr** [comment]
Some things that come to mind:
- only implemented for F1, not for F4
- not implemented for all SPI devices (SPI3 missing)
- NSS pin handling only for SPI2 or any other slave select handling

**Comment by kirkscheper** [comment]
OK, well I can take a look at these. I will think of a simple way to test these with the same bluetooth module (the only slave device I have) to make sure the code works.

**Comment by dewagter** [comment]
Maybe we can put a bluetooth dongle on a lisaM / Mx to test F1/F4.

Testing SPI slave on SPI1 will not be easy with the aspirin on the NSS pin
however.

To test SPI slave with slave select we also have CHIMU. @openuas might be
able to help here.

**Comment by OpenUAS** [comment]
OK, I'll rip the CHIIMU from the Moska airframe (not trivial) after at least one testflight with it.

**Comment by kirkscheper** [comment]
Hey Eric, I thought we discussed this and decided not to bother with the 
CHIMU... I will find a different solution. No worries.

**Comment by flixr** [comment]
Closing this as it works at least for the F1.
