### ISSUE TITLE
Asprini 2.2 driver startup unstable

### ISSUE THREAD

**Issue by esden** [paparazzi/paparazzi#333]
The current Aspirin 2.2 driver in master is not able to initialise the MPU-6000 after flashing the firmware. 
It also fails to initialise when the voltage is not very stable at startup. For example when using the switching voltage regulators on Lisa/L that cause the voltage to bounce at startup.

Repowering the board solves the issue in most cases and the MPU-6000 as well as all other sensors are initialising properly.

**Comment by esden** [comment]
Is this still an issue? Since Lisa/M(X) V2.1 with integrated aspirin V2.2 I have not run into this issue any more. Is it a hardware issue related to the aspirin having more capacitance on the power rail?

**Comment by flixr** [comment]
I have never had this issue in the first place, so I don't know...

**Comment by EwoudSmeur** [comment]
I have not seen this issue for a long time, so I think we can close it.
