### ISSUE TITLE
FAILSAFE setting useless if AHRS needs GPS

### ISSUE THREAD

**Issue by martinmm** [paparazzi/paparazzi#358]
The airframe FAILSAFE settings will no longer work if the AHRS algorithm relies on GPS (e.g. DCM). The auto1 mode will also not work after a couple of seconds without GPS in that case.

Reproducibility: Always, reset GPS in GCS

Possible solution: Switch to predefined control surface positions if GPS is lost? Try to run the algorithm without GPS if no fix?
##

**Comment by OpenUAS** [comment]
As aircraft could fall from the sky (tm) at least 'ill give it an label...

**Comment by gautierhattenberger** [comment]
what should we do with this ? there is no real way to compensate the AHRS without any speed information anyway

**Comment by podhrmic** [comment]
I don't have a good idea either. Maybe it is "not an issue" since it is so stale?
