### ISSUE TITLE
new feature: GCS load/save waypoint's

### ISSUE THREAD

**Issue by agressiva** [paparazzi/paparazzi#403]
I suggest a GCS menu item to save / load waypoint positions to/from a file.
For example:
Open Flight plan editor and put some waypoints in new position (absolute coordinate) and save waypoint positions in the file.

In the field, the waypoint file can be loaded and the waypoints go to correct absolute positions.

A good option is to export the waypoint's as KML or other common file type so the waypoints can be made in google earth using the same names(number) used in FP editor.

Is a good idea save only waypoint with absolute coordinates or a option to chose what waypoint will be saved.

I think that HOME WP not be changed by this file.

If a waypoint have ALTitude defined this will be imported too.
##

**Comment by podhrmic** [comment]
Just one use case - we are reflashing the autopilot before each flight, simply to make sure it has the correct code - so you dont have to remember when it was last flashed and what code was uploaded. Imho this can be moved to a later release.

**Comment by quadrotorx250** [comment]
Hi, I'm not sure it's right place to say this but let me say my first comment:)
I think it's better to make reflashing easier and faster! some time it's really difficult to access the hardware and plug usb or programmer port(in my case stlink is catastrophic! ).

I have an idea which could make reflashing easier, my idea is to use datalink or wireless modules(like WiFi) for programming. As I see we can program MCU's by serial protocol, so if datalink works in transparent mode we could program very easily !?

**Comment by podhrmic** [comment]
@quadrotorx250  - Best if you create a new issue and describe your idea in more detail there - looks like you have a feature request, so then it would be good to describe the use case, functionality etc.

**Comment by flixr** [comment]
@quadrotorx250 you should already be able to flash via datalink (xbee), although I haven't used this feature in years...

**Comment by gautierhattenberger** [comment]
closing as won't be fixed in current GCS
see https://github.com/paparazzi/paparazzi/projects/2
