### ISSUE TITLE
Enhancement GCS: KML sector load

### ISSUE THREAD

**Issue by agressiva** [paparazzi/paparazzi#404]
I suggest that sector can be loaded from default KML file.
Its much easy to create a KML file than the sector using paparazzi dtd.

**Comment by gautierhattenberger** [comment]
Note that it is already possible to display a sector from a kml file in the GCS. It is only able to use polyline (converted to closed polygon for display) and it doesn't generate embedded code.
```
<sectors>
  <kml file="mykml.kml"/>
</sectors>
```

**Comment by agressiva** [comment]
jep, i tested some time ago.

What i want is the possibility to load KML files direct in CGS maps/load_sector
Its very usefull in the field.
I use it as guide to move the waypoint manually in the field.

may be it be called KML OVERLAY

**Comment by flixr** [comment]
@agressiva so you are basically missing a menu in the GCS to load a KML sector for display only, right?

**Comment by agressiva** [comment]
right.
