### ISSUE TITLE
[drivers][modules] External magnetometer

### ISSUE THREAD

**Issue by Drumettaz** [paparazzi/paparazzi#407]
Disable LisaM / aspirin 2 hmc5883 magnetometer when using mag_hmc_58xx.xml module.
When flying large rotorcrafts, magnetic perturbations are sometime too high to be corrected by software only (using mag current calibration)
It's then necessary to use an external magnetometer such as HMC5883 via I2C, in order to be able to move it away from magnetic perturbations. 
This can be done using module hmc_58xx.xml, but then with Lisa M / aspirin 2, the onboard magnetometer needs to be disabled.
Maybe this feature can be added soon as aspirin 2 driver is being refactored at the moment (issue #190 )?

**Comment by flixr** [comment]
Closing as you can now select the mag to use by specifying the ABI sender id of the mag.
(introduced with #https://github.com/paparazzi/paparazzi/pull/856)

The orientation of the external mag still needs to be the same as the IMU, so #197 is still open...
