### ISSUE TITLE
replace spi_slave_hs with normal spi slave code

### ISSUE THREAD

**Issue by flixr** [paparazzi/paparazzi#492]
The spi_slave_hs is only implemented for lpc21 and is currently used for e.g. imu/ahrs_chimu.
This should be replaced by the normal spi_slave code using transaction queues so we can remove the duplicate slave_hs code

**Comment by flixr** [comment]
@gautierhattenberger I suggest we also close this as WONTFIX as it seems to work where needed but we won't be building new autopilots based on LPC21...

**Comment by gautierhattenberger** [comment]
agreed
