### ISSUE TITLE
rotorcraft vertical guidance: feed-forward throttle problematic with adaptive nominal throttle estimation

### ISSUE THREAD

**Issue by flixr** [paparazzi/paparazzi#527]
When using the adaptive throttle estimation together with vertical guidance loops (e.g. in nav or z-hold) the quad often gives too much throttle when giving some roll/pitch commands.

When running the vertical guidance hover_loop, there is an "extra attitude thrust" in the feedforward term, the 1/(cos theta \* cos phi) coeff.
This is meant to keep applying the same thrust in the direction of the gravity vector when banking.

The problem is probably if you use both together... the adaptive nominal throttle estimation takes the thrust command as input and actually assumes that this is vertical thrust.
Which especially in these roll/pitch cases is not true... now if you disable the "extra attitude thrust", your thrust command stays nearly the same and you don't get such a false estimate.
So the adaptive estimation should really get the actually applied thrust in the direction of the gravity vector, and ideally also after saturation/mixing.

Summary of tests from @softsr:
1. no adaptive throttle, no extra attitude thrust - looks fine, didn't see even any big signs of loosing altitude while rolling/pitching
2. no adaptive throttle, but with extra attitude thrust - pretty the same as 1.
3. adaptive throttle with ADAPT_NOISE_FACTRO = 1.5, no extra attitude thrust - only sometime, on hard curves I could trigger light climbing, but it is not really hard
4. adaptive throttle and extra attitude thrust - very very easy triggering hard jumping on even not really hard curves
##

**Comment by flixr** [comment]
reminder: needs re-testing
weird simulation results might have been due to a NPS bug fixed with #1132

**Comment by gautierhattenberger** [comment]
too old
