### ISSUE TITLE
unreliable flashing via DFU/luftboot (e.g. Lisa/M)

### ISSUE THREAD

**Issue by flixr** [paparazzi/paparazzi#593]
Seems flashing LisaM via DFU/luftboot is unreliable.

Adding a CRC check might solve this issue, but brings other problems:
- backwards compatibility?
- no start condition check in luftboot due to size constraints?
- no more flashing of option registers, is that needed anyway?

@molnarkares has worked on this...
##

**Comment by flixr** [comment]
I never use this, so I have no clue how reliable it is...

**Comment by flixr** [comment]
If someone encounters this problem, please provide more details...

**Comment by agressiva** [comment]
Hi Felix, i tried to use the DFU with pixhawk but it not work.
It upload the firmware but the board not work.

To upload the firmware to pixhawk i generate a hex file then use a program to convert hex to dfu file and then upload to pixhawk using a dfu utility.

**Comment by gautierhattenberger** [comment]
timeout
