### ISSUE TITLE
JSBSim models for other multicopter configurations needed

### ISSUE THREAD

**Issue by flixr** [paparazzi/paparazzi#595]
We currently only have JSBSim models for quadrotors in + configuration:
simple_quad (with front/back motor turning clock wise) and simple_quad_ccw (with front/back motor turning counter clock wise).

We are missing some other common configurations (in order of importance):
- quadrotor in X configuration
- "standard" hexacopter
- "standard" octocopter
- Y6 hexacopter
- ?

**Comment by hooperfly** [comment]
@esden @flixr FYI, I'm working on a Hexa X model for use with jsbsim. Still tweaking the model but should have something ready in the next week or so.

**Comment by hooperfly** [comment]
@flixr JSBSim model for a hexacopter submitted for review.

**Comment by flixr** [comment]
Closing this since we now at least have some hexa and ocoto configurations, thanks to @hooperfly
