### ISSUE TITLE
Expected behavior of "Load background tile" GCS menu option incorrect

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#607]
Expected behavior of "Load background tile" GCS menu option incorrect

Background: There is no easy way to reload tiles already once downloaded and available in cache for a certain area. A helpful fix could be extending the "Load background tile" behavior.

Prerequisite: Have already an older filled maptile cache

Reproduce:
1. Start GCS with the options _-maps_fill -maps_no_cache_
2. Right click on GCS map
3. Choose "Load background tile"

Expected behavior when one of the GCS Menu options _Map Policy_ -> _CacheOrHttp_ or _NoCache_ is enabled is to "Load background tile"  a tile of position under mouse cursor, the old one removed.

![nomaptilereferesh](https://f.cloud.github.com/assets/483944/1818381/dcf83430-6ffd-11e3-88fd-32a8538facff.jpg)
##

**Comment by gautierhattenberger** [comment]
closing as won't be fixed in current GCS
see https://github.com/paparazzi/paparazzi/projects/2
