### ISSUE TITLE
Paparazzi 6.0 wishlist 

### ISSUE THREAD

**Issue by podhrmic** [paparazzi/paparazzi#620]
I've seen some great progress on the Paparazzi code in the last weeks and months, and I think it is time to start thinking about the future. Hence Paparazzi 6.0^^

The main advantage of Paparazzi over its competitors (i.e. Pixhawk https://pixhawk.ethz.ch/px4/modules/pixhawk) is modularity (i.e. various modules and reconfigurability through xml config files) and support for multiple boards (e.g. Lia/Lisa M, Discovery board, etc.). 

The disadvantage is imho lots of legacy code (e.g. fixedwing and its dual MCU configuration, coming from the ancient Classix board http://paparazzi.enac.f/wiki/Classix ), and not thorough testing of new features (which is hard due to multiple boards/platforms supported). Also the Ground Station software isn't the sexiest looking or most user friendly one.

Here is how I envision the future:
_Flawlessly running autopilot code. Vast majority of boards used will be based on STM32F4 chip, because its superior power and low price. Paparazzi will offer both Real Timer version and standard (bare-metal) version of the code. The ground station software will either get new look or it will be possible to use a third-party GCS. There will be templates for new code, so making for example hovercraft autopilot will be very easy._

Which comes to a little wishlist for next major version:
1. Refactor (and remove obsolete code) fixedwing firmware code, add templates for autopilot and control loops (new firmwares can be easily added)
2. RT Paparazzi fully integrated, offering new possibilities with failsafe tasks, data logging and autopilot monitoring
3. Code thoroughly tested, code works on all boards as well as on old TWOGs
4. ? Maybe ? drop support for LPC chips and focus on STM32Fx architecture
5. MAVLINK wrapper for IVY (so Paparazzi can talk to QGroundControl http://qgroundcontrol.org/ )

I am intentionally skipping some other important things (like code upload features) which are already in the issue list.

Please let me know what is your opinion on this.
##

**Comment by podhrmic** [comment]
Removing the milestone since this conversation is not relevant for 6.0 anymore as some of the proposed changes are already on the way, but most likely wont be fixed in time for 6.0.

**Comment by flixr** [comment]
Well, we might just make the next release as v5.10.... and keep this for an actual v6.0...

**Comment by podhrmic** [comment]
I see, well it would actually make sense to call the next release 5.10

**Comment by gautierhattenberger** [comment]
6.0 is already released
