### ISSUE TITLE
improve AGL interface e.g. from Sonar

### ISSUE THREAD

**Issue by TobiasMue** [paparazzi/paparazzi#685]
with the sonar_distance being part of ABI it is not possible anymore to asses it directly from the flight plan...
would be great to have something like GetPosAGL()
AGL could or should be part of the state interface or ins?

**Comment by gautierhattenberger** [comment]
now there is also the `agl_dist` module (http://docs.paparazziuav.org/latest/module__agl_dist.html). Maybe not as nice as being integrated to state interface, but is it enough to close this ? at least for next milestone ?

**Comment by TobiasMue** [comment]
so you want to close this just to open new one? thats fine with me - but then we should have at least an example how to access AGL in flight plan...

**Comment by gautierhattenberger** [comment]
There is now an example in the flight plans (conf/flight_plans/competitions/IMAV2014_vision.xml)
Closing issue.
