### ISSUE TITLE
UART missing messages in the ARDrone

### ISSUE THREAD

**Issue by karlito139** [paparazzi/paparazzi#743]
The UART seams to be missing around half of the data when using the regular paparazzi library. When trying to send data with an arduino connected to the USB port of the ARDrone I can get around 2s of data, then I lose 2s of data, then back 2S. The value of 2s is what I was able to measure in my case. I also got a lot of picks in the data.

To get those result I was using an arduino that send a counter that was incremented whenever a message was send. The resulting telemetry measurements are those :

![14_06_06__14_56_12](https://cloud.githubusercontent.com/assets/2040179/3200543/a60f4866-ed7d-11e3-93a2-1625e92c4a65.png)

I can go around that issue by using directly the serial port as a file, using code taken from the fireswarm project. In that case the results are as expected :

![14_06_06__15_0_11](https://cloud.githubusercontent.com/assets/2040179/3200545/a9aa24b4-ed7d-11e3-8cf5-0b6bdc983259.png)

The test code is available as a module (Arduino2Ardrone2) in the branch UARTbug in my fork of papaprazzi : karlito139/paparazzi. The code used in the arduino is available in the repo : karlito139/arduino2ardrone2 in the branch counter.

**Comment by flixr** [comment]
Ups, closed because I wrote `might also fix #743` in the commit...
@karlito139 @OpenUAS would be great if you could test this with the fixes merged in master (with #1110) again...
Plz reopen if still an issue...
