### ISSUE TITLE
AR.Drone vertical state estimation

### ISSUE THREAD

**Issue by EricPoppe** [paparazzi/paparazzi#765]
This issue concerns the vertical velocity and altitude estimation on the AR.Drone 2 without using the sonar or a gps module.  I hope this information helps in improving Paparazzi. It is all I can come up with regarding this problem. Unfortunately I do not have the time to properly investigate these problems or gather any required data.

The vertical velocity estimation issue is explained in the mailing list, the mentioned problems still hold: http://lists.paparazziuav.org/AR-Drone-vertical-velocity-without-SONAR-td15386.html.

The altitude estimate issue in short: at high tilt angle and velocity the estimated altitude increases with respect to the actual altitude.

Why do I think so: When flying at high pitch angles and high velocity while using an altitude hold mode the AR.Drone visibly descents. However, the measurement show acceptable altitude tracking. 

The figures below show the tilt angle and altitude during a 30 degrees tilt flight of only a few seconds. At the end of the flight displayed in the graphs the AR.Drone hits the ground while the altitude measurement is still at 2.5 meters. I did a geo init just before the flight and the starting point of the AR.Drone is visibly about 3.5 above the ground. Just before hitting the ground I switch back to 0 tilt angle after which the drone shoots up to the starting altitude (not shown in the graphs). 

Probably the measured pressure decreases due to the airflow around the drone. In that case it can only be compensated if the velocity is measured.

The graphs below are generated using an adjusted control algorithm but with the original Paparazzi state estimation.

![30_ndi_altitude](https://cloud.githubusercontent.com/assets/6338035/3444333/745b2394-012d-11e4-9053-396bd62ebc3c.jpg)
![30_ndi_tilt](https://cloud.githubusercontent.com/assets/6338035/3444332/7459a154-012d-11e4-990f-fce64cfce18d.jpg)

**Comment by gautierhattenberger** [comment]
@OpenUAS can someone at TUDelft look at this issue, or is it still a problem ?

**Comment by fvantienen** [comment]
Timed out, not sure if still a problem
