### ISSUE TITLE
radio_control.xml, flight_plan.xml, etc. should not be mandatory for the build system

### ISSUE THREAD

**Issue by flixr** [paparazzi/paparazzi#78]
From Antoine: I find it annoying that the build system makes it mandatory for everything built with paparazzi to have a radio_control.xml, a flight_plan, a telemetry file, a settings file etc... I've build many things with paparazzi ( unit test, antenna tracker, motor controllers, lab benches etc....) and having a flight plan for a motor controller does not really make sense.

e.g. radio.xml is totally superfluous for spektrum equiped vehicles

The code generation tools enforce that and even some ground segment programs ( server won't log anything for a device that does not have a flight plan for example )

**Comment by gautierhattenberger** [comment]
Closing this issue since it will not be solved independently of #246
And it is way too old
