### ISSUE TITLE
[superbitrf] does not bind with DX7

### ISSUE THREAD

**Issue by flixr** [paparazzi/paparazzi#811]
superbitrf radio_control does not bind with the DX7 (neither with nor without SUPERBITRF_FORCE_DSM2)
##

**Comment by tjsch** [comment]
I am using the DX6i and am having trouble getting the transmitter to bind with the Lisa/S and the USB dongle. What is best method to get this up and running for a fixed wing airframe?  

For reference it is in force DSM2 mode. If I just bind the Lisa it claims to bind but I cannot actuate any servos/motor. If I bind the dongle and the Lisa at the same time the dongle will show that the bind was successful, but the radio status light on the Lisa just keeps blinking. I have also put the dongle in debug mode to get the transmitter ID. But even putting in this ID I cannot get everything to bind. Thanks in advance for the help!

**Comment by OpenUAS** [comment]
@tjsch, thanks for describing the issue in more detail. BTW reguar usage questions are better asked on the [http://wiki.paparazziuav.org/wiki/Contact#Mailing_List mailing list], you have more chance of a response. After all this is just an issue tracker ;) no not forum

**Comment by gautierhattenberger** [comment]
reopen if needed
