### ISSUE TITLE
No more upload when LINK is red

### ISSUE THREAD

**Issue by dewagter** [paparazzi/paparazzi#820]
When your ground station shows link-timeout (RED) after 5 seconds, then you can also not send any new command, flightplan, setting, ... to the plane...

When you have LEDs on your modem you can clearly see that as long as LINK is green, a flightplan command (e.g. standby) is being sent, but as soon as LINK goes RED, it does not send anything anymore.

Surely this is not intended? Do you know if this is a LINK / SERVER / GCS issue

**Comment by flixr** [comment]
Added the `-ac_timeout` parameter to link with a0bee87, if you set it to a negative number, the aircraft should never be regarded as dead and uplink never disabled.
Is that enough to close this issue, or do you want add something to completely remove/kill an AC from the ground segment?

**Comment by gautierhattenberger** [comment]
@dewagter does the timeout fix enough to close the issue?

**Comment by gautierhattenberger** [comment]
closing due to feedback timeout
