### ISSUE TITLE
commands from GCS are not retried

### ISSUE THREAD

**Issue by alonsoac** [paparazzi/paparazzi#849]
Hello. It sometimes happens that when the GCS sends a packet it does not arrive. So one has to try clicking on the button several times until the change is applied in the GCS screen. It could also be I supposed that the aircraft receives the command but the confirmation of the change is not received by the GCS.

This for example can cause a very dangerous situation where the kill button is pressed in the GCS but the command is not received and not retried and one has to click again, confirm again, which could take several seconds during which the motors are running.

So, first question: is this the expected behavior on non-perfect telemetry links or is this a some other bug or problem I have?
Second, if this is the expected behavior what do you think about making a retry system which would resend the packets.  Possible config options:
- how many retries
- how often to retry
- what condition stops the retries ( for example when the change to a var is confirmed, or when a new value for the same var is sent from the GCS the old value should not be retried).
  I suppose this configs might vary by type of message or variable, so for example some messages might be sent a few times but something like a kill would be sent quickly as long as necessary.

Perhaps this is a feature to be implemented in the ivy bus or the server and not every client?
##

**Comment by gautierhattenberger** [comment]
I would like to close this, not sure it is even a good idea in the end

**Comment by podhrmic** [comment]
it would make the com protocol much more complicated, so I am in favor of closing
