### ISSUE TITLE
Pressing C not centering active UA on MAP middle but window middle

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#874]
As a user I would like to center the current UA on the map pressing the C. At the moment it look like it centers it, but it centers on complete windows X,Y not 2dMap XY middle. Can be reporoduced bu iming a flight pressing C and then Zoom in a lot. 

This issue is in real testflight quite important to not lose time while zooming in to track 
UA behaviour

**Comment by flixr** [comment]
Should also be solved with #1059

**Comment by OpenUAS** [comment]
Very nice, thx! will test.
