### ISSUE TITLE
Support for Pixhawk RTFHawkboards types not available

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#881]
As a user I ike to use Paparazzi icw the Fixhawk, Pixhawk, RTFHawk,  boards http:// and at the moment I can not. Hardware to test is available. A "RAW" implementation with inter_MCU is the feature wished for.

Hardware:
http://witespyquad.gostorego.com/rtfhawk-2-4.html

 A ChibiOS or nuttix is not in this issue scope.

**Comment by flixr** [comment]
FYI, I started to make board files, etc. for the px4fmu v2 (aka pixhawk), see px4fmu_v2.4 branch...

**Comment by flixr** [comment]
See also #1384

**Comment by flixr** [comment]
Closed with addition of the PX4IO board, intermcu improvements, etc:
https://github.com/paparazzi/paparazzi/pull/1551
https://github.com/paparazzi/paparazzi/pull/1566
https://github.com/paparazzi/paparazzi/pull/1569
https://github.com/paparazzi/paparazzi/pull/1587
https://github.com/paparazzi/paparazzi/pull/1592
