### ISSUE TITLE
Naming of PPRZ_MIN PPRZ_MAX unclear

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#882]
History gave us the PPRZ_MIN PPRZ_MAX defines. If all code is fixed to use the values and no hard coded 9600 anymore anywhere, it is time to think about a more discriptive name.

**Comment by flixr** [comment]
I don't see any reason to change it, what would be the benefit?

**Comment by podhrmic** [comment]
I suggest closing since it is not an issue. @flixr @OpenUAS ?
