### ISSUE TITLE
Modules not well documented in code

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#883]
As a use I want to simply use modules in my autopilot. At the moment this is troublsome since the documentation of Modules is to sparse. 

- Description text in Modules sourcecode needs to be updated.

**Comment by flixr** [comment]
Goes together with #896

**Comment by flixr** [comment]
Not specific enough, closing...
Most modules are documented ok... but of course can still be improved in most cases... just doesn't warrant such a generic issue.
