### ISSUE TITLE
Speeding up Gaia in simulator give inconsistent behaviour

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#887]
If one use Gaia speedup time we get un-expcted behavious in sim, e.g. the link loss counter. A sped up sim should behave as a realtime sim
##

**Comment by OpenUAS** [comment]
Yes, indeed. thanks, but one of the benifits of a sim is we can speed up time...the issue is that if we speed up time, the behaviour is not correct. If I test fr e.g. links loss in speedup sim on a long complex flghtplan one cannt test for it. It alwails hops to loss...no doubt there are more parameters but this was just the most problematic one.

**Comment by gautierhattenberger** [comment]
We agree it is an issue but it is a "won't fix" for now.
