### ISSUE TITLE
A lot of airframes included in a release do not compilen

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#888]
As a use I expect airframefiles delivered alongside a released PPRZ version to compile. A lot of them do not.

Some of the issues found with airframes:

- Not updated to the values of release
- Not comment at all or othere explanation
- To many different ones without specific demonstration of uniqueness
- Wrong gains
- Wrongly named
- Wrong directory
- Lots of 0/1 and not TRUE FALSE with boolean values.
- Lots of USE_xyz and no TRUE FALSE added
- No use of PPRZ_MAX in e.g. Failsafe_value="3000"/> should be PPRZ_MAX*.3 or so
- Not cleand up through the airframe creator
- No modern example reflecting current PPRZ abilities

**Comment by podhrmic** [comment]
@OpenUAS @flixr is this resolved with #1249 ?
I am not really sure how to approach all of the mentioned issues, but maybe good enough to close since it has milestone for v5.6?

**Comment by flixr** [comment]
I think we still have a little more cleanup to do...

**Comment by podhrmic** [comment]
OK, can you be more specific? Looks like everybody has his own style of making airframe config files (i.e. firmware section on the top vs. bottom) so it is hard to say which one should be preferred.

**Comment by flixr** [comment]
I vote for firmware section at the top, then modules, then the rest...
apparently the airframe editor that @dewagter started is at least able to reorder everything in the airframe file, but I have never used that so far...

Ideally we would probably only have a representative set of airframes in examples at the end (e.g. commonly used combinations and ones showing some nice features).
Maybe move those airframe files that we only use to test the compilation with other boards/subsystems/config in a test folder or so...
While that would be nice, it is not a blocking issue for me...

Not sure what else @OpenUAS wants to do here....

**Comment by flixr** [comment]
@OpenUAS Unless someone steps up to make the airframe files nicer NOW, can we close this, or at least remove the v5.6 milestone?

**Comment by flixr** [comment]
feedback timeout, removing from milestone
will be assumed ok and closed without further feedback soon...
