### ISSUE TITLE
Video Papaget zooms with GCS 2D map in one go

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#889]
Video Papaget zooms with GCS 2D map canvas in one go and should not. A size is defined for the papget, it should stay that size. And example is incuded:

![pprzbugzoomvideopapaget01](https://cloud.githubusercontent.com/assets/483944/4885814/52eea1f2-6377-11e4-8745-d25c0b8931e8.jpg)
![pprzbugzoomvideopapaget02](https://cloud.githubusercontent.com/assets/483944/4885813/52edcc0a-6377-11e4-9efd-b260d3a33607.jpg)
![pprzbugzoomvideopapaget03](https://cloud.githubusercontent.com/assets/483944/4885815/52f088dc-6377-11e4-8823-4ab3977335dd.jpg)

**Comment by gautierhattenberger** [comment]
@OpenUAS can you test with video_papget_fix branch ?

**Comment by gautierhattenberger** [comment]
up ? otherwise I'll merge it since it seems to work according to my test

**Comment by flixr** [comment]
If there is no feedback from @OpenUAS, you can just merge if it works for you...
