### ISSUE TITLE
The isInside function does not work with Lat Lon coordinates in flightplan

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#892]
As a user I like to use Lat Lon coordinates in flightplan and still be able to test If the AC isInside a certain sector and at the moment ca not.

**Comment by OpenUAS** [comment]
Don't recall what my real issues was :(, Anyhow just tested an area defined by lat/lon and use inside function, it worked.

**Comment by OpenUAS** [comment]
Will test.

**Comment by OpenUAS** [comment]
Will test for fixedwing

**Comment by flixr** [comment]
Could you plz not remove the "incomplete" labels until we have an actual description of the issue...
