### ISSUE TITLE
Module naming inconsistent

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#896]
Mudule names, directorties and setting naming sould be consistend across all modules and is not:

For example: flight_benchmark,  <load name="flight_benchmark.xml"/>
Directory should also be called    flight_benchmark
Just as the settings document should be called "flight_benchmark.xml"

**Comment by flixr** [comment]
Could you please make a list of modules which you think need cleanup?

**Comment by gautierhattenberger** [comment]
Closing for now.
If more cleaning is needed, please provide a list of relevant modules.
