### ISSUE TITLE
Module naming not explanatory enough

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#905]
Outome: Modules with more sensible explainatory naming

For example, just to gice the issue some direction:

Cam_Control modules

To Camera Movement Control

Digital_Cam modules

Camera Trigger and Set Interface Modules

GPS modules

INS and AHRS modules

special case

Vehicle_Interface modules

**Comment by flixr** [comment]
Can we plz combine this with #896 ?

**Comment by OpenUAS** [comment]
Fine lest clean on the go... to 5.8 and higher
