### ISSUE TITLE
Config documents belonging together not based on XML document name

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#907]
Config documents belonging together should be based on XML document name, not the "Nice Name" IN the document.

One would get things like

Could not open file: /home/theuser/paparazzi/conf/simulator/jsbsim/aircraft/MyThing.xml

JSBSim failed to open the configuration file: /home/theuser/paparazzi/conf/simulator/jsbsim/aircraft/MyThing.xml

maybe even with a postfix like: MyThing_jsbsim.xml so putting them in one directory is still also possible and also avoids confusion.

If I would have a different "Nice name"
##

**Comment by flixr** [comment]
@OpenUAS As you can specify the name of the JSBSim model to use in your airframe file I don't see the issue here.
At the time of writing this issue, was it just not clear that you can set this or is there some remaining issue that you see?
If not I would like to close this issue.

**Comment by OpenUAS** [comment]
Assigned to self, for over next release, no closing yet.

**Comment by flixr** [comment]
Could you plz still try to explain where you see the issue here?

**Comment by podhrmic** [comment]
@OpenUAS any progress here? Or should we close it as is?

**Comment by gautierhattenberger** [comment]
timeout
