### ISSUE TITLE
Not enough space in horizontal menu with multiple AC in air

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#909]
Having multiple AC in air the strategy of the horizontal menu does not work well, or at all, see illustrative image:

![pprz_multipleplaneissueingui_nospace](https://cloud.githubusercontent.com/assets/483944/4887871/98d3b764-6388-11e4-86f2-a9d7309ce8d3.jpg)
##

**Comment by gautierhattenberger** [comment]
Is it really necessary to keep that open ? When you fly several UAVs, it is just as simple to use laptop with an adapted screen. For single UAV flights, small screens are usually good enough.

**Comment by gautierhattenberger** [comment]
closing as won't be fixed in current GCS
see https://github.com/paparazzi/paparazzi/projects/2
