### ISSUE TITLE
No option to recenter AC on mapcenter automatically

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#911]
As a use I would like to have to be able to set a command option to the GCS map to move x,y with my aircraft center if it leaves the map, or has a proximity distance to 2D map border.

As user I realize if tiles are used and a big zoom factor it means a heavier load on the computer processor running the GCS.
##

**Comment by gautierhattenberger** [comment]
closing as won't be fixed in current GCS
see https://github.com/paparazzi/paparazzi/projects/2
