### ISSUE TITLE
Resizing plotter to small window make labels unreadable

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#916]
When resizing logging windows labels get very small upto unreadable.

Note the screenshot is **not** resized

![labels_upto_unreadable](https://cloud.githubusercontent.com/assets/483944/4888723/954fa47a-638f-11e4-80ca-153997a644f5.jpg)

Setting a cap on minimum via parameter could be an enhancement.
##

**Comment by gautierhattenberger** [comment]
this is a GTK limitation, there is not many things we can do except changing the GUI design completely
