### ISSUE TITLE
GCS message box does not show AC anme when Speech name is defined

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#918]
Having a speech_name defined as e.g. MK1_EEE and an AC name as "supernicelongname" the TEXT in the warning console box shows the speech name and should not. 

Sometime one sets Speech name to a short one to avoid other messaage interuption, but setting this should not influence the console text displayed.

![gcs_displays_speechname_not_airframename](https://cloud.githubusercontent.com/assets/483944/4888936/a18fee96-6391-11e4-942d-49c52fd0f4d7.jpg)
##

**Comment by gautierhattenberger** [comment]
timeout + wontfix
