### ISSUE TITLE
Support for Naze32 full board not available

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#921]
As a user I ike to use Paparazzi icw the full Naze32 Afroflight opensource boards rev. v5 and at the moment I can not.

Base:
http://code.google.com/p/afrodevices/wiki/AfroFlight32

**Comment by OpenUAS** [comment]
I  gave way one of my board over a TU who is involved in adding support now..

**Comment by flixr** [comment]
@martinmm already has some improvements to make the firmware smaller so it can actually fit in the naze32 (and similar like the CC3D).

**Comment by martinmm** [comment]
and it is running on a Naze32 already, will commit that asap

**Comment by hooperfly** [comment]
That's good news. Lots of naze32's boards floating around, so to speak. Nice work.

**Comment by martinmm** [comment]
Unfortunately Naze32 are only 2-layer PCBs and create a lot of noise that disturbs the GPS receiver

**Comment by flixr** [comment]
@martinmm any progess on this front?

**Comment by flixr** [comment]
Support for naze32 rev4 as part of #1452

**Comment by flixr** [comment]
I think we can close this since we merge #1452, at least it works on my flip32 (naze32 rev4 clone)?
@martinmm had problems that the baro was not working on his rev5 board.
@OpenUAS maybe you can check with your boards as well?

**Comment by agressiva** [comment]
i will test too.

**Comment by flixr** [comment]
@OpenUAS @agressiva @hooperfly have you guys had a chance to test this yet?
Can we close this issue or did you find problems with the current support?

**Comment by agressiva** [comment]
working great on my miniquad.

**Comment by flixr** [comment]
Is that a rev4 or rev5? If it's a rev5, does the baro work?

**Comment by agressiva** [comment]
i am using an board similar to rev5. 
baro work.

**Comment by flixr** [comment]
:-)
Closing this then..
