### ISSUE TITLE
replace GnoDruid with GtkAssistant

### ISSUE THREAD

**Issue by flixr** [paparazzi/paparazzi#923]
Usage of GnoDruid, the OCaml wrapper for deprecated [GnomeDruid](https://developer.gnome.org/libgnomeui/stable/GnomeDruid.html) should probably be replaced by GtkAssistant in pc_common.ml

See also https://developer.gnome.org/gtk2/stable/gtk-migrating-GtkAssistant.html
##

**Comment by gautierhattenberger** [comment]
not relevant anymore
