### ISSUE TITLE
[flight_plan] add possibility to have RC commands for manual and auto1, from fp in auto2

### ISSUE THREAD

**Issue by flixr** [paparazzi/paparazzi#930]
# Curent situation:

1) One wants to fly an fixedwing aircraft in full RC mode, that works just fine.
2) One wants to fly an fixedwing aircraft in a "specific not NAV mode" e.g. AUTO1, in fixedwing defined, attitude is stabilized but RC imput can be "injected" realtime

e.g a function like _crowbrake level_ can be RC commanded which is handy for tuning fully autonomous landings and the needed settings for this to work out well.
Or command for example a _rudded deflection_ manually for a roll and pitch stabilized flight during crosswind landings to lineup to the runway while testing autonomous landings.

3) One wants to have RC enhanced control in "specific not NAV mode" e.g. AUTO1, but the control should be able to be commanded from the autopilot again if in full autonomous mode (AUTO2).

E.g an amount of crowbrake "strengh" value set via a RC slider input when in AUTO1 but and Autopilot commanded value in AUTO2.
# The issue

At the moment if a RC command is set in the airframe configuration section "auto_rc_command" there is no way to let AUTO2 override this behaviour.

We already have `rc_commands`, `auto_rc_commands` and `ap_only_commands`. If you want to pass on the RC commands in manual and auto1, but use command them from flight plan in auto2 we currently have no out-of-the-box solution.
# Wished outcome

As a user I would like to be able to command my crowbraking or other control via RC if in RC or an "AUTO1" like mode, but the commanded control should be able to be commanded by the Autopilot when in "AUTO2" mode.
At the moment when defined in the section "auto_rc_commands", it is still RC commanded when in "AUTO2" mode and that is not wished for.
# Reflections

Looking at modes in Rotorcraft and keeping integration in the future in mind, we basically have something like this in fixedwing by default for setting modes:

MANUAL = AP_MODE_RC_DIRECT
AUTO1 = AP_MODE_ATTITUDE_DIRECT
AUTO2 = AP_MODE_NAV

Note that one could conclude that it is unfortunate that there is a naming "Auto" this make discussion more confusing. Likely the current naming if compared to rotorcraft needs a refresh and could maybe better fully renamed exactly like it is in Rotorcraft.
# Solution RFC

Plz add change this RFC part to define what needs to be changed to get to our wished outcome and as a proper solution for #878.
## RFC intro

The behaviour of  `auto_rc_commands` **should** have been: to define what RC commands I can use in a "specific mode" as long as it is not AP_MODE_NAV a.k.a. AUTO2 for a fixedwing
The defined behaviour is, when we look at the naming of the element sadly not so clear if we see it in context of the naming of the existing element "ap_only_commands" 
## Our option 1

A solution could be to add another ELEMENT e.g. named like `auto_rc_only_commands` and change current behaviour of `auto_rc_commands` not to have RC invluence if in AP_MODE_NAV 

Where in the new to add  `auto_rc_only_commands` if written verbose we would mean:

`When I'm in an "specific not NAV mode(autox)", the given commands are then listened to **only** to RC COMMANDS, **even** overruling NAV mode AP given commands.`

There the already existing element of `auto_rc_commands` should then if written out verbose **newly** to: 

`When I'm in an auto mode "specific mode(auto)" these will have of influence if RC commanded, but **never** used if in AP mode.`

The question of naming remains, it could well be `ap_rc_commands` with a reverse behaviour,
thus if defined in element `ap_rc_commands` meaning if in any other mode than AUTO2 RC commands defined can be used else AUTO2 can take over
## Our Option 2

Maybe there is a better way with already existing element naming and using exclusion and thus not adding another element.
# Note

We rather find an appropriate name now than changing it again later...

As noted before; we might want to rething the way we specify stuff like that anyway, also considering rotorcrafts where this manua/auto1/auto2 doesn't map so well.

Elaboration and more options wished for, TIA
##

**Comment by flixr** [comment]
@dewagter since nobody worked on this, I suggest to move this to v6.0 or do you have something?

**Comment by dewagter** [comment]
I think this only an issue for fixedwing.
Postpone or nofix is OK.
