### ISSUE TITLE
improve and properly use module dependencies

### ISSUE THREAD

**Issue by flixr** [paparazzi/paparazzi#940]
We already have a basic dependency mechanism for modules, but it needs to be improved and used properly.

Right now you can depend on a list of other modules (either using the name or xml file name) or specify a conflict with another module.
This is not quite enough... sometimes we need to have a dependency on at least one module "providing" a specifc functionality/interface.

E.g. for the digital_cam modules we have several implementations:
- digital_cam.xml (using gpio, should probabyl be renamed to digita_cam_gpio.xml anyway)
- digital_cam_uart.xml
- digital_cam_i2c.xml
- digital_cam_servo.xml

The proposed digital_cam_shoot_rc.xml needs to depend on one of these modules. So either we have to set the name of all of those to `digital_cam` so it doesn't matter which one you have added or add the possibilty to specify several different options with some "logical OR" in depend.
I guess it would make sense to allow multiple `depend` nodes and add the possibility to specify OR dependencies similar to debian depends like `<depend require="digital_cam_uart | digital_cam_servo | digital_cam"/>`

Another alternative would be to add something like a `provides="foo"` attribute to modules so you can specify an "abstract" fuctionality/interface that it provides and that other modules can depend on.

Also if a dependency is not satified it currently only prints a warning, when used properly everywhere we should throw an error...
##

**Comment by flixr** [comment]
We should probably also consider ordering the init functions according to the dependencies (first init modules that are dependencies of others).
E.g. the init order is currently crucial for modules calling `cv_add` in init, see also #1539

**Comment by gautierhattenberger** [comment]
there is a working dependency for modules now #2669
