### ISSUE TITLE
Not possible to store TBOH in persistent settings for defined parts

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#943]
As a user I like to store certain values in the autopilot persistent and cannot simply at the moment.
like a Time between overhaul (abbreviated as TBO or TBOH)

We could start of with storing something of servo usage. This to be able to read certain values and give a maintenance warning after a threshold is passed.

E.g. just for a start add a counter measuring the total of arm movement of a servo(divided by 1000 or whatever value to make the value to store easier, or some round robing stuff) Just as an example, when AP is adds all commanded deflections during flight and with certain interval stores this value.
When AP is restarted, AP grabs value and continues counting. If threshold defined is reached e.g. a message is send...or some other action we can come up with
##

**Comment by gautierhattenberger** [comment]
Probably a good idea, but really not a priority
