### ISSUE TITLE
No actuator curve settable

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#949]
As a user I woud like to be able to set non liniar behavior of a actuator depending on AP PPRZ value input at the moment I cannnot set a curve.

A PPRZ_MAX*1byte resolution in Y and 8 control points on X would already be helpful.

Specfically airbrakes and flaps on throtle or airspeed coupling would be helpful
##

**Comment by flixr** [comment]
We now have helicopter throttle curve support with #1437

**Comment by gautierhattenberger** [comment]
Closing for timeout, will be implement if someone really needs it
