### ISSUE TITLE
sourcecode comment language not unified to English everywhere

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#952]
As a develper I like to be able to simply read the comments in the sourcecode and the moment I cannot if we assume English should be de language of choice there.

There are still quite some French comments.

Action: Replace French comments with English comments

**Comment by flixr** [comment]
IMHO this is issue is useless without a list of files which still have french comments...
@OpenUAS, I propose to close this issue due to feedback timeout soon if no one can provide any actual cases...

**Comment by IHaveADrone** [comment]
https://github.com/paparazzi/paparazzi/blob/master/doc/checklist/checklist.tex
I'm not sure if this counts as code, but it looks French to me.

**Comment by IHaveADrone** [comment]
https://github.com/paparazzi/paparazzi/blob/master/sw/lib/ocaml/geometry_2d.ml
https://github.com/paparazzi/paparazzi/blob/master/sw/lib/ocaml/geometry_3d.ml
https://github.com/paparazzi/paparazzi/blob/master/sw/lib/ocaml/gtk_image.ml
https://github.com/paparazzi/paparazzi/blob/master/sw/ground_segment/tmtc/GSM/SMS_Ground_UDtest_final.c

I'm not familiar with these parts of the code, I just grep French words.

**Comment by gautierhattenberger** [comment]
All this files are out-dated, they should be removed soon.

**Comment by gautierhattenberger** [comment]
Closing this issue, remaining files won't be updated since it is too much work for stuff nobody cares about
