### ISSUE TITLE
add more tests for math and run them on CI

### ISSUE THREAD

**Issue by flixr** [paparazzi/paparazzi#954]
We need more tests for the math library (apart from the few "manual" test_algebra/geodetic ones in sw/airborne/tests).
See also #819
##

**Comment by flixr** [comment]
We have some very basic example tests for the math lib in tests/math...

@fvantienen @EwoudSmeur you guys said you would also help to add some more test cases if we had the basics set up...

**Comment by kirkscheper** [comment]
Will add my self here to follow this issue. I will add some more tests soon.
