### ISSUE TITLE
Adding variables to real time plotter from messages is painfull

### ISSUE THREAD

**Issue by kevindehecker** [paparazzi/paparazzi#966]
1. The telemetry has to mouse dragged from the messages to the real time plotter. I can name at least a few ways this can be made more user friendly from a GUI perspective. E.g. creating a dropdown menu inside realtime plotter with the available messages, double clicking a message will add it to first opened realtime plotter, a right click context menu on a message "send this msg to window [id]" ). In terms of GUI design, the first option would be best  (related stuff should be close-by).

2. Currently, when dragging a message, the users has to plan a "drag route" such that the messages window is not touched because otherwise the message window will change its selection. This is undesirable behavior.

Especially in the field on small laptop screens with touch-pads this is annoying. . . Amplified by:

3. AFAIK the realtime plotter lacks a feature to save the configuration. So after each restart (due to rebuilding, accidental, etc) the user has to repeat. Please add a feature such that the realtimeplotter remembers its last configuration (contents, plot settings, window config).

**Comment by kevindehecker** [comment]
ok, tnx

**Comment by alonsoac** [comment]
This is not working as expected when the Messages window is showing multiple aircraft. When I start dragging the tab for the selected a/c disappears. When it appears later it is no longer selected.

**Comment by gautierhattenberger** [comment]
fixed in master with 9c877f5624e6189f4491bceffb2533609c780ec4
