### ISSUE TITLE
Support for all config in CI builds not available

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#974]
As a user I simply want to use and take a look at the provided Airframes (and also other conf files) without being confronted with non working configurations.

It is oftentimes the case configs are not working, although provided in a stable release.

A favored option would be to add all te confs to the CI tests

**Comment by flixr** [comment]
With #1134 you can now easily test compile your own custom conf without changing the conf/conf.xml symlink:
```
CONF_XML=$PAPARAZZI_HOME/conf/airframes/CDW/conf.xml prove tests/examples
```

**Comment by flixr** [comment]
So basically what we need to do is create confs for the airframe files that we want tested (i.e. specify what settings, telemetry, flightplan, radio, ... should go with the airframe file, so that we have something that can be built)
Creating a job for that is then easy...

**Comment by podhrmic** [comment]
Again, should be fixed with #1249 
@flixr @OpenUAS are we good for v5.6?

**Comment by flixr** [comment]
Well that depends if we want builds running for more/all airframes or not...

**Comment by flixr** [comment]
Added `test_all_confs` make target in 5c9a42bab44aa430c1c1c8d43b1b88bbf4f56971.
This make target will try to find all confs and build all aircrafts/targets in there...
It is now used in a scheduled nightly build on https://semaphoreci.com/paparazziuav/paparazzi as travis doesn't support scheduled builds...

**Comment by flixr** [comment]
While not all aircrafts/targets in all confs build, the infrastructure is there and will be built nightly... so closing this...
