### ISSUE TITLE
ARdrone2 drops out of sky in att zhold

### ISSUE THREAD

**Issue by kevindehecker** [paparazzi/paparazzi#977]
Using Master v5.2_stable I experience sudden drops out of the sky with the ARdrone2 during hovering in zhold. After the drop, it tends to recover to the correct height. An example can be viewed in this [video](https://drive.google.com/file/d/0B_SZaF2Rt7FreVBIRDJZTnlibXM/view?usp=sharing) at 1:50 - 1:58. A log from a similar event is available from [here](https://drive.google.com/file/d/0B_SZaF2Rt7FrdUY5VHZUYVM0TnM/view?usp=sharing)

I used the standard ardrone2_raw.xml airframe, only disabled the magneto. (so both sonar and baro should be enabled).

**Comment by OpenUAS** [comment]
With PPRZ > 5.4 needs a re-test, lost of improvements of sensor readings. Helping with at least > 200+ flights in CyberZoo I did not encounter this behaviour anymore ( but lots of other issue)  >;-)

**Comment by gautierhattenberger** [comment]
Is this still an issue ?

**Comment by gautierhattenberger** [comment]
closing for feedback timeout
re-open if needed
