### ISSUE TITLE
Limitation of maximum zoom in flight plan GCS too strict

### ISSUE THREAD

**Issue by kevindehecker** [paparazzi/paparazzi#992]
When flying indoors in our flight arena and using the mouse wheel to zoom in, I find the zooming restriction in GCS far too strict. I regularly cannot see the difference between way points due to this restriction, while they are in fact significant in such a close environment. 
##

**Comment by gautierhattenberger** [comment]
closing as won't be fixed in current GCS
see https://github.com/paparazzi/paparazzi/projects/2
