### ISSUE TITLE
Detect when GCS needs to be restarted

### ISSUE THREAD

**Issue by kevindehecker** [paparazzi/paparazzi#994]
After for instance a chance in the flight plan in which I changed a hot key to jump to a new block, apparently a restart of GCS is required before it is applied. However the user is not informed to do so. Either a notification of some sort should be displayed in GCS or GCS should cope with the changes automatically.
##

**Comment by gautierhattenberger** [comment]
closing as won't be fixed in current GCS
see https://github.com/paparazzi/paparazzi/projects/2
